# Full Pipeline 04: Fine-Tune Multiple Policies (Including Attention DQN)

This notebook fine-tunes multiple RL policies on the merged full-pipeline state and exports refreshed validation/locked-test actions.

Included policies:
- DQN (SB3)
- A2C (SB3)
- PPO (SB3)
- AttentionDQN (custom agent in ml/agents/dqn_agent.py)

Inputs:
- output/full_pipeline/model_state_weekly_hmm_news.csv
- optional existing checkpoints under output/full_pipeline/ or output/models/

Outputs:
- output/full_pipeline/*_finetuned checkpoints
- output/full_pipeline/*_validation_actions_finetuned.csv
- output/full_pipeline/*_locked_test_actions_finetuned.csv

In [8]:
from pathlib import Path
import contextlib
import io
import random
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from IPython.display import display
from stable_baselines3 import A2C, DQN, PPO

REPO_ROOT = None
for candidate in [Path.cwd(), *Path.cwd().parents]:
    if (candidate / "full_pipeline").exists() and (candidate / "scripts").exists():
        REPO_ROOT = candidate
        break
if REPO_ROOT is None:
    raise RuntimeError("Could not locate the repo root.")

PIPELINE_ROOT = REPO_ROOT / "full_pipeline"
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
if str(PIPELINE_ROOT) not in sys.path:
    sys.path.insert(0, str(PIPELINE_ROOT))

from evaluation import EvaluationConfig
from ml.agents import AttentionDQNAgent
from ml.hyperparameter_config import load_hyperparameter_config
from ml.training_utils import evaluate_episode, train_dqn_finrl
from _pipeline_utils import (
    OUTPUT_DIR,
    build_full_pipeline_artifacts,
    make_rl_env,
    prepare_rl_inputs,
    rollout_agent_on_split,
    save_action_frame,
)

SEED = 42
np.random.seed(SEED)
random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)

pd.set_option("display.max_columns", 220)
pd.set_option("display.width", 220)

In [9]:
# Fine-tuning configuration loaded from shared YAML config
CONFIG_PATH = REPO_ROOT / "configs" / "rl_hyperparameters.yaml"
HP_CONFIG = load_hyperparameter_config(CONFIG_PATH, fast_mode=False)
CFG = HP_CONFIG.values

USE_CUDA = torch.cuda.is_available()
DEVICE = "cuda" if USE_CUDA else "cpu"

if USE_CUDA:
    # RTX 4080-oriented defaults: enable TF32 and cuDNN autotuning for throughput.
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True
    torch.backends.cudnn.benchmark = True

# Reduce noisy stderr logs when state auto-build triggers HMM grid search.
SUPPRESS_HMM_BUILD_STDERR = True

SEQ_LEN = int(CFG["general"]["sequence_length"])
EVAL_CONFIG = EvaluationConfig(
    transaction_cost=float(CFG["environment"]["transaction_cost"]),
    risk_penalty=float(CFG["environment"]["volatility_penalty"]),
    risk_window=int(CFG["environment"]["lookback_vol"]),
)

ENABLED_POLICIES = ["DQN", "A2C", "PPO", "ATTENTION_DQN"]
RUN_OUTPUT_DIR = OUTPUT_DIR / "100000"
FORCE_RETRAIN = True

POLICY_CONFIGS = {
    "DQN": {
        "learning_rate": float(CFG["dqn"]["learning_rate"]),
        "exploration_fraction": float(CFG["dqn"]["exploration_fraction"]),
        "exploration_final_eps": float(CFG["dqn"]["exploration_final_eps"]),
        "target_update_interval": int(CFG["dqn"]["target_update_interval"]),
        "buffer_size": int(CFG["dqn"]["buffer_size"]),
        "batch_size": int(CFG["dqn"]["batch_size"]),
        "gamma": float(CFG["dqn"]["gamma"]),
        "eval_freq": int(CFG["dqn"]["eval_freq"]),
        "early_stopping_patience": int(CFG["dqn"]["early_stopping_patience"]),
        "warmup_timesteps": int(CFG["dqn"]["train_timesteps"]),
        "finetune_timesteps": int(CFG["dqn"]["train_timesteps"]),
    },
    "A2C": {
        "learning_rate": float(CFG["a2c"]["learning_rate"]),
        "gamma": float(CFG["a2c"]["gamma"]),
        "n_steps": int(CFG["a2c"]["n_steps"]),
        "ent_coef": float(CFG["a2c"]["ent_coef"]),
        "vf_coef": float(CFG["a2c"]["vf_coef"]),
        "warmup_timesteps": int(CFG["a2c"]["train_timesteps"]),
        "finetune_timesteps": int(CFG["a2c"]["train_timesteps"]),
    },
    "PPO": {
        "learning_rate": float(CFG["ppo"]["learning_rate"]),
        "n_steps": int(CFG["ppo"]["n_steps"]),
        "batch_size": int(CFG["ppo"]["batch_size"]),
        "n_epochs": int(CFG["ppo"]["n_epochs"]),
        "gamma": float(CFG["ppo"]["gamma"]),
        "gae_lambda": float(CFG["ppo"]["gae_lambda"]),
        "clip_range": float(CFG["ppo"]["clip_range"]),
        "ent_coef": float(CFG["ppo"]["ent_coef"]),
        "vf_coef": float(CFG["ppo"]["vf_coef"]),
        "warmup_timesteps": int(CFG["ppo"]["train_timesteps"]),
        "finetune_timesteps": int(CFG["ppo"]["train_timesteps"]),
    },
    "ATTENTION_DQN": {
        "learning_rate": float(CFG["dqn"]["learning_rate"]),
        "gamma": float(CFG["dqn"]["gamma"]),
        "buffer_capacity": int(CFG["dqn"]["buffer_size"]),
        "batch_size": int(CFG["dqn"]["batch_size"]),
        "target_update_freq": max(250, int(CFG["dqn"]["target_update_interval"] // 4)),
        "epsilon_start": float(CFG["dqn"]["exploration_initial_eps"]),
        "epsilon_end": float(CFG["dqn"]["exploration_final_eps"]),
        "epsilon_decay": 3000,
        "warmup_episodes": 6,
        "finetune_episodes": 10,
    },
}

CHECKPOINTS = {
    "DQN": {
        "base": RUN_OUTPUT_DIR / "dqn_hmm_news_base.zip",
        "finetuned": RUN_OUTPUT_DIR / "dqn_hmm_news_finetuned.zip",
        "fallback": REPO_ROOT / "output" / "models" / "dqn_finrl_agent.zip",
    },
    "A2C": {
        "base": RUN_OUTPUT_DIR / "a2c_hmm_news_base.zip",
        "finetuned": RUN_OUTPUT_DIR / "a2c_hmm_news_finetuned.zip",
        "fallback": REPO_ROOT / "output" / "models" / "a2c_finrl_agent.zip",
    },
    "PPO": {
        "base": RUN_OUTPUT_DIR / "ppo_hmm_news_base.zip",
        "finetuned": RUN_OUTPUT_DIR / "ppo_hmm_news_finetuned.zip",
        "fallback": REPO_ROOT / "output" / "models" / "ppo_finrl_agent.zip",
    },
    "ATTENTION_DQN": {
        "base": RUN_OUTPUT_DIR / "attention_dqn_hmm_news_base.pt",
        "finetuned": RUN_OUTPUT_DIR / "attention_dqn_hmm_news_finetuned.pt",
        "fallback": REPO_ROOT / "output" / "models" / "attention_dqn_agent.pt",
    },
}

print(f"Hyperparameter config: {CONFIG_PATH.relative_to(REPO_ROOT)}")
print(f"Resolved mode: {'fast' if HP_CONFIG.fast_mode else 'full'}")
print(f"Device: {DEVICE}")
if USE_CUDA:
    print("CUDA GPU:", torch.cuda.get_device_name(0))

print("Enabled policies:", ENABLED_POLICIES)
print(f"Run output dir: {RUN_OUTPUT_DIR.relative_to(REPO_ROOT)}")
print(f"Force retrain: {FORCE_RETRAIN}")
for policy_name in ENABLED_POLICIES:
    paths = CHECKPOINTS[policy_name]
    print(f"{policy_name} checkpoints:")
    print("  base:", paths["base"].relative_to(REPO_ROOT))
    print("  finetuned:", paths["finetuned"].relative_to(REPO_ROOT))
    print("  fallback:", paths["fallback"].relative_to(REPO_ROOT))

Hyperparameter config: configs\rl_hyperparameters.yaml
Resolved mode: full
Device: cuda
CUDA GPU: NVIDIA GeForce RTX 3050 Laptop GPU
Enabled policies: ['DQN', 'A2C', 'PPO', 'ATTENTION_DQN']
Run output dir: output\full_pipeline\100000
Force retrain: True
DQN checkpoints:
  base: output\full_pipeline\100000\dqn_hmm_news_base.zip
  finetuned: output\full_pipeline\100000\dqn_hmm_news_finetuned.zip
  fallback: output\models\dqn_finrl_agent.zip
A2C checkpoints:
  base: output\full_pipeline\100000\a2c_hmm_news_base.zip
  finetuned: output\full_pipeline\100000\a2c_hmm_news_finetuned.zip
  fallback: output\models\a2c_finrl_agent.zip
PPO checkpoints:
  base: output\full_pipeline\100000\ppo_hmm_news_base.zip
  finetuned: output\full_pipeline\100000\ppo_hmm_news_finetuned.zip
  fallback: output\models\ppo_finrl_agent.zip
ATTENTION_DQN checkpoints:
  base: output\full_pipeline\100000\attention_dqn_hmm_news_base.pt
  finetuned: output\full_pipeline\100000\attention_dqn_hmm_news_finetuned.pt
  fallback: output\models\attention_dqn_agent.pt

In [10]:
moment_state_path = OUTPUT_DIR / "model_state_weekly_hmm_news_moment.csv"
base_state_path = OUTPUT_DIR / "model_state_weekly_hmm_news.csv"

if moment_state_path.exists():
    state_path = moment_state_path
    print(f"Using MOMENT RL state: {state_path.relative_to(REPO_ROOT)}")
else:
    state_path = base_state_path
    if not state_path.exists():
        print(f"Missing pipeline state at {state_path.relative_to(REPO_ROOT)}. Building full pipeline artifacts...")
        if SUPPRESS_HMM_BUILD_STDERR:
            stderr_buffer = io.StringIO()
            with contextlib.redirect_stderr(stderr_buffer):
                artifacts = build_full_pipeline_artifacts()
        else:
            artifacts = build_full_pipeline_artifacts()
        built_state = artifacts["artifact_paths"]["merged_state"]
        print(f"Built pipeline state: {Path(built_state).relative_to(REPO_ROOT)}")
    else:
        print(f"Using existing pipeline state: {state_path.relative_to(REPO_ROOT)}")

prepared = prepare_rl_inputs(state_path=state_path)
frame = prepared["frame"]

train_env = make_rl_env(prepared, split="train", seq_len=SEQ_LEN, config=EVAL_CONFIG)
val_env = make_rl_env(prepared, split="validation", seq_len=SEQ_LEN, config=EVAL_CONFIG)
test_env = make_rl_env(prepared, split="locked_test", seq_len=SEQ_LEN, config=EVAL_CONFIG)

state_dim = int(train_env.observation_space.shape[-1])
action_dim = int(train_env.action_space.n)

display(prepared["dataset"].describe_splits())
display(prepared["dataset"].describe_feature_blocks())
print("Feature count:", len(prepared["feature_cols"]))
print("Posterior columns:", prepared["posterior_cols"])
print("State dim:", state_dim)
print("Action dim:", action_dim)

class AttentionAgentAdapter:
    """Adapter that exposes .predict for custom AttentionDQNAgent."""

    def __init__(self, core_agent):
        self.core_agent = core_agent

    def predict(self, obs, deterministic=True):
        action = self.core_agent.select_action(obs, training=not deterministic)
        return np.array([action], dtype=np.int64), None

def train_attention_dqn(agent, env, episodes, deterministic_eval=False):
    history = []
    for ep in range(int(episodes)):
        obs, _ = env.reset()
        done = False
        ep_reward = 0.0

        while not done:
            action = agent.select_action(obs, training=True)
            next_obs, reward, terminated, truncated, _ = env.step(action)
            done = bool(terminated or truncated)
            agent.store_transition(obs, int(action), next_obs, float(reward), done)
            _ = agent.train_step()
            obs = next_obs
            ep_reward += float(reward)

        agent.episode_end()
        eval_reward = float(ep_reward)
        if deterministic_eval:
            eval_reward = float(evaluate_episode(AttentionAgentAdapter(agent), env, deterministic=True)["reward"])
        history.append({"episode": ep + 1, "reward": float(ep_reward), "eval_reward": eval_reward})

    return pd.DataFrame(history)

Using MOMENT RL state: output\full_pipeline\model_state_weekly_hmm_news_moment.csv

         split  rows      start        end
0        train   189 2017-05-19 2020-12-25
1   validation   105 2021-01-01 2022-12-30
2  locked_test   167 2023-01-06 2026-03-13

    block  n_columns                                    example_columns
0   price         99  spy_ret_1d, spy_ret_5d, spy_ret_20d, spy_vol_5...
1   macro         31  bamlh0a0hym2_level, bamlh0a0hym2_chg_5d, cfnai...
2  regime          4  regime_filtered, regime_viterbi, filtered_prob...
3    text          5  news_finbert_compound_spy, news_finbert_compou...

Feature count: 135
Posterior columns: ['filtered_prob_regime_0', 'filtered_prob_regime_1']
State dim: 141
Action dim: 7

## Load Existing Policies or Bootstrap Base Models

If a policy checkpoint is not found, the notebook trains a lightweight warmup model and saves it under output/full_pipeline.

In [11]:
RUN_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

models = {}
bootstrap_notes = []

def _try_load_sb3_model(algorithm_cls, candidate_paths, env, device):
    load_errors = []
    for ckpt_path in candidate_paths:
        if not ckpt_path.exists() or ckpt_path.suffix != ".zip":
            continue
        try:
            model = algorithm_cls.load(ckpt_path, env=env, device=device)
            return model, ckpt_path, load_errors
        except ValueError as exc:
            # Most common here: observation/action space mismatch after feature changes.
            load_errors.append(f"{ckpt_path.name}: {exc}")
    return None, None, load_errors

for policy_name in ENABLED_POLICIES:
    paths = CHECKPOINTS[policy_name]
    params = POLICY_CONFIGS[policy_name]
    candidate_paths = [] if FORCE_RETRAIN else [paths["finetuned"], paths["base"], paths["fallback"]]

    if policy_name == "DQN":
        loaded_model, loaded_ckpt, load_errors = _try_load_sb3_model(
            DQN, candidate_paths, train_env, DEVICE
        )
        if loaded_model is not None:
            models[policy_name] = loaded_model
            bootstrap_notes.append({"policy": policy_name, "status": f"loaded {loaded_ckpt.name}"})
        else:
            if load_errors:
                print("Skipping incompatible DQN checkpoint(s):")
                for err in load_errors:
                    print("  -", err)
            warmup = train_dqn_finrl(
                train_env=train_env,
                val_env=val_env,
                total_timesteps=int(params["warmup_timesteps"]),
                eval_freq=int(params["eval_freq"]),
                early_stopping_patience=int(params["early_stopping_patience"]),
                learning_rate=float(params["learning_rate"]),
                exploration_fraction=float(params["exploration_fraction"]),
                exploration_final_eps=float(params["exploration_final_eps"]),
                target_update_interval=int(params["target_update_interval"]),
                buffer_size=int(params["buffer_size"]),
                batch_size=int(params["batch_size"]),
                device=DEVICE,
                verbose=1,
            )
            models[policy_name] = warmup["agent"]
            models[policy_name].save(paths["base"])
            bootstrap_notes.append({"policy": policy_name, "status": f"bootstrapped -> {paths['base'].name}"})

    elif policy_name == "A2C":
        loaded_model, loaded_ckpt, load_errors = _try_load_sb3_model(
            A2C, candidate_paths, train_env, DEVICE
        )
        if loaded_model is not None:
            models[policy_name] = loaded_model
            bootstrap_notes.append({"policy": policy_name, "status": f"loaded {loaded_ckpt.name}"})
        else:
            if load_errors:
                print("Skipping incompatible A2C checkpoint(s):")
                for err in load_errors:
                    print("  -", err)
            model = A2C(
                "MlpPolicy",
                train_env,
                learning_rate=float(params["learning_rate"]),
                gamma=float(params["gamma"]),
                n_steps=int(params["n_steps"]),
                ent_coef=float(params["ent_coef"]),
                vf_coef=float(params["vf_coef"]),
                verbose=1,
                device=DEVICE,
            )
            model.learn(total_timesteps=int(params["warmup_timesteps"]), progress_bar=True)
            model.save(paths["base"])
            models[policy_name] = model
            bootstrap_notes.append({"policy": policy_name, "status": f"bootstrapped -> {paths['base'].name}"})

    elif policy_name == "PPO":
        loaded_model, loaded_ckpt, load_errors = _try_load_sb3_model(
            PPO, candidate_paths, train_env, DEVICE
        )
        if loaded_model is not None:
            models[policy_name] = loaded_model
            bootstrap_notes.append({"policy": policy_name, "status": f"loaded {loaded_ckpt.name}"})
        else:
            if load_errors:
                print("Skipping incompatible PPO checkpoint(s):")
                for err in load_errors:
                    print("  -", err)
            model = PPO(
                "MlpPolicy",
                train_env,
                learning_rate=float(params["learning_rate"]),
                n_steps=int(params["n_steps"]),
                batch_size=int(params["batch_size"]),
                n_epochs=int(params["n_epochs"]),
                gamma=float(params["gamma"]),
                gae_lambda=float(params["gae_lambda"]),
                clip_range=float(params["clip_range"]),
                ent_coef=float(params["ent_coef"]),
                vf_coef=float(params["vf_coef"]),
                verbose=1,
                device=DEVICE,
            )
            model.learn(total_timesteps=int(params["warmup_timesteps"]), progress_bar=True)
            model.save(paths["base"])
            models[policy_name] = model
            bootstrap_notes.append({"policy": policy_name, "status": f"bootstrapped -> {paths['base'].name}"})

    elif policy_name == "ATTENTION_DQN":
        attn_agent = AttentionDQNAgent(
            state_dim=state_dim,
            action_dim=action_dim,
            seq_len=SEQ_LEN,
            learning_rate=float(params["learning_rate"]),
            gamma=float(params["gamma"]),
            epsilon_start=float(params["epsilon_start"]),
            epsilon_end=float(params["epsilon_end"]),
            epsilon_decay=int(params["epsilon_decay"]),
            buffer_capacity=int(params["buffer_capacity"]),
            batch_size=int(params["batch_size"]),
            target_update_freq=int(params["target_update_freq"]),
            use_dueling=True,
            device=DEVICE,
        )
        loaded_attention = False
        for ckpt_path in candidate_paths:
            if not ckpt_path.exists() or ckpt_path.suffix != ".pt":
                continue
            try:
                attn_agent.load_checkpoint(str(ckpt_path))
                bootstrap_notes.append({"policy": policy_name, "status": f"loaded {ckpt_path.name}"})
                loaded_attention = True
                break
            except Exception as exc:
                print(f"Skipping incompatible ATTENTION_DQN checkpoint {ckpt_path.name}: {exc}")

        if not loaded_attention:
            warmup_hist = train_attention_dqn(
                attn_agent,
                train_env,
                episodes=int(params["warmup_episodes"]),
            )
            attn_agent.save_checkpoint(str(paths["base"]))
            bootstrap_notes.append({"policy": policy_name, "status": f"bootstrapped -> {paths['base'].name}"})
            display(warmup_hist.tail(3))

        models[policy_name] = attn_agent

bootstrap_df = pd.DataFrame(bootstrap_notes)
display(bootstrap_df)

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
=== Training DQN Agent with FinRL ===
Device: cuda
Total timesteps: 100000
Evaluation frequency: 5000
Early stopping patience: 100000

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 0.0559   |
|    exploration_rate | 0.952    |
| time/               |          |
|    episodes         | 4        |
|    fps              | 6558     |
|    time_elapsed     | 0        |
|    total_timesteps  | 756      |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 0.188    |
|    exploration_rate | 0.904    |
| time/               |          |
|    episodes         | 8        |
|    fps              | 472      |
|    time_elapsed     | 3        |
|    total_timesteps  | 1512     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.2e-05  |
|    n_updates        | 511      |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 0.257    |
|    exploration_rate | 0.856    |
| time/               |          |
|    episodes         | 12       |
|    fps              | 312      |
|    time_elapsed     | 7        |
|    total_timesteps  | 2268     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.05e-05 |
|    n_updates        | 1267     |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 0.289    |
|    exploration_rate | 0.808    |
| time/               |          |
|    episodes         | 16       |
|    fps              | 254      |
|    time_elapsed     | 11       |
|    total_timesteps  | 3024     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.3e-05  |
|    n_updates        | 2023     |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 0.354    |
|    exploration_rate | 0.761    |
| time/               |          |
|    episodes         | 20       |
|    fps              | 233      |
|    time_elapsed     | 16       |
|    total_timesteps  | 3780     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.3e-06  |
|    n_updates        | 2779     |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 0.462    |
|    exploration_rate | 0.713    |
| time/               |          |
|    episodes         | 24       |
|    fps              | 220      |
|    time_elapsed     | 20       |
|    total_timesteps  | 4536     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.54e-07 |
|    n_updates        | 3535     |
----------------------------------

Validation at step 5000: reward=-0.1017

  -> New best validation reward!

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 0.558    |
|    exploration_rate | 0.665    |
| time/               |          |
|    episodes         | 28       |
|    fps              | 211      |
|    time_elapsed     | 25       |
|    total_timesteps  | 5292     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.07e-06 |
|    n_updates        | 4291     |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 0.652    |
|    exploration_rate | 0.617    |
| time/               |          |
|    episodes         | 32       |
|    fps              | 204      |
|    time_elapsed     | 29       |
|    total_timesteps  | 6048     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 0.000113 |
|    n_updates        | 5047     |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 0.716    |
|    exploration_rate | 0.569    |
| time/               |          |
|    episodes         | 36       |
|    fps              | 200      |
|    time_elapsed     | 33       |
|    total_timesteps  | 6804     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.45e-07 |
|    n_updates        | 5803     |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 0.791    |
|    exploration_rate | 0.521    |
| time/               |          |
|    episodes         | 40       |
|    fps              | 197      |
|    time_elapsed     | 38       |
|    total_timesteps  | 7560     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.7e-08  |
|    n_updates        | 6559     |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 0.864    |
|    exploration_rate | 0.473    |
| time/               |          |
|    episodes         | 44       |
|    fps              | 194      |
|    time_elapsed     | 42       |
|    total_timesteps  | 8316     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.03e-06 |
|    n_updates        | 7315     |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 0.947    |
|    exploration_rate | 0.425    |
| time/               |          |
|    episodes         | 48       |
|    fps              | 194      |
|    time_elapsed     | 46       |
|    total_timesteps  | 9072     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.99e-08 |
|    n_updates        | 8071     |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.04     |
|    exploration_rate | 0.378    |
| time/               |          |
|    episodes         | 52       |
|    fps              | 194      |
|    time_elapsed     | 50       |
|    total_timesteps  | 9828     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.75e-08 |
|    n_updates        | 8827     |
----------------------------------

Validation at step 10000: reward=-0.1481

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.12     |
|    exploration_rate | 0.33     |
| time/               |          |
|    episodes         | 56       |
|    fps              | 192      |
|    time_elapsed     | 55       |
|    total_timesteps  | 10584    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.36e-07 |
|    n_updates        | 9583     |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.21     |
|    exploration_rate | 0.282    |
| time/               |          |
|    episodes         | 60       |
|    fps              | 191      |
|    time_elapsed     | 59       |
|    total_timesteps  | 11340    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.31e-08 |
|    n_updates        | 10339    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.28     |
|    exploration_rate | 0.234    |
| time/               |          |
|    episodes         | 64       |
|    fps              | 191      |
|    time_elapsed     | 63       |
|    total_timesteps  | 12096    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.56e-05 |
|    n_updates        | 11095    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.35     |
|    exploration_rate | 0.186    |
| time/               |          |
|    episodes         | 68       |
|    fps              | 191      |
|    time_elapsed     | 66       |
|    total_timesteps  | 12852    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.16e-08 |
|    n_updates        | 11851    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.42     |
|    exploration_rate | 0.138    |
| time/               |          |
|    episodes         | 72       |
|    fps              | 191      |
|    time_elapsed     | 71       |
|    total_timesteps  | 13608    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 9.55e-08 |
|    n_updates        | 12607    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.48     |
|    exploration_rate | 0.0903   |
| time/               |          |
|    episodes         | 76       |
|    fps              | 190      |
|    time_elapsed     | 75       |
|    total_timesteps  | 14364    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.01e-07 |
|    n_updates        | 13363    |
----------------------------------

Validation at step 15000: reward=-0.0814

  -> New best validation reward!

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.56     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 80       |
|    fps              | 188      |
|    time_elapsed     | 80       |
|    total_timesteps  | 15120    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.31e-08 |
|    n_updates        | 14119    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.62     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 84       |
|    fps              | 187      |
|    time_elapsed     | 84       |
|    total_timesteps  | 15876    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.2e-08  |
|    n_updates        | 14875    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.68     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 88       |
|    fps              | 185      |
|    time_elapsed     | 89       |
|    total_timesteps  | 16632    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 9.74e-08 |
|    n_updates        | 15631    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.74     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 92       |
|    fps              | 186      |
|    time_elapsed     | 93       |
|    total_timesteps  | 17388    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.73e-08 |
|    n_updates        | 16387    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.79     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 96       |
|    fps              | 186      |
|    time_elapsed     | 97       |
|    total_timesteps  | 18144    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.06e-05 |
|    n_updates        | 17143    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.84     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 100      |
|    fps              | 186      |
|    time_elapsed     | 101      |
|    total_timesteps  | 18900    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.68e-08 |
|    n_updates        | 17899    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 1.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 104      |
|    fps              | 186      |
|    time_elapsed     | 105      |
|    total_timesteps  | 19656    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.51e-08 |
|    n_updates        | 18655    |
----------------------------------

Validation at step 20000: reward=-0.1338

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.06     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 108      |
|    fps              | 186      |
|    time_elapsed     | 109      |
|    total_timesteps  | 20412    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.52e-07 |
|    n_updates        | 19411    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.17     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 112      |
|    fps              | 186      |
|    time_elapsed     | 113      |
|    total_timesteps  | 21168    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.87e-07 |
|    n_updates        | 20167    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.27     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 116      |
|    fps              | 186      |
|    time_elapsed     | 117      |
|    total_timesteps  | 21924    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.43e-08 |
|    n_updates        | 20923    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.36     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 120      |
|    fps              | 186      |
|    time_elapsed     | 121      |
|    total_timesteps  | 22680    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 8.12e-07 |
|    n_updates        | 21679    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.44     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 124      |
|    fps              | 187      |
|    time_elapsed     | 125      |
|    total_timesteps  | 23436    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.97e-08 |
|    n_updates        | 22435    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.52     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 128      |
|    fps              | 187      |
|    time_elapsed     | 129      |
|    total_timesteps  | 24192    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.35e-06 |
|    n_updates        | 23191    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.58     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 132      |
|    fps              | 187      |
|    time_elapsed     | 133      |
|    total_timesteps  | 24948    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.09e-07 |
|    n_updates        | 23947    |
----------------------------------

Validation at step 25000: reward=-0.1432

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.65     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 136      |
|    fps              | 187      |
|    time_elapsed     | 137      |
|    total_timesteps  | 25704    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.9e-08  |
|    n_updates        | 24703    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.71     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 140      |
|    fps              | 187      |
|    time_elapsed     | 141      |
|    total_timesteps  | 26460    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.29e-06 |
|    n_updates        | 25459    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.76     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 144      |
|    fps              | 187      |
|    time_elapsed     | 145      |
|    total_timesteps  | 27216    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.28e-07 |
|    n_updates        | 26215    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.81     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 148      |
|    fps              | 187      |
|    time_elapsed     | 149      |
|    total_timesteps  | 27972    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.39e-07 |
|    n_updates        | 26971    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.83     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 152      |
|    fps              | 187      |
|    time_elapsed     | 152      |
|    total_timesteps  | 28728    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.1e-07  |
|    n_updates        | 27727    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.87     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 156      |
|    fps              | 188      |
|    time_elapsed     | 156      |
|    total_timesteps  | 29484    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.72e-08 |
|    n_updates        | 28483    |
----------------------------------

Validation at step 30000: reward=-0.1900

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.88     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 160      |
|    fps              | 187      |
|    time_elapsed     | 161      |
|    total_timesteps  | 30240    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.69e-06 |
|    n_updates        | 29239    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.91     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 164      |
|    fps              | 187      |
|    time_elapsed     | 165      |
|    total_timesteps  | 30996    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.46e-07 |
|    n_updates        | 29995    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 168      |
|    fps              | 187      |
|    time_elapsed     | 168      |
|    total_timesteps  | 31752    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 9.88e-08 |
|    n_updates        | 30751    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 172      |
|    fps              | 188      |
|    time_elapsed     | 172      |
|    total_timesteps  | 32508    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.38e-06 |
|    n_updates        | 31507    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 176      |
|    fps              | 188      |
|    time_elapsed     | 176      |
|    total_timesteps  | 33264    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.85e-07 |
|    n_updates        | 32263    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 180      |
|    fps              | 188      |
|    time_elapsed     | 180      |
|    total_timesteps  | 34020    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 0.000291 |
|    n_updates        | 33019    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 184      |
|    fps              | 188      |
|    time_elapsed     | 184      |
|    total_timesteps  | 34776    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.26e-07 |
|    n_updates        | 33775    |
----------------------------------

Validation at step 35000: reward=-0.2560

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 188      |
|    fps              | 188      |
|    time_elapsed     | 188      |
|    total_timesteps  | 35532    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.81e-07 |
|    n_updates        | 34531    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 192      |
|    fps              | 188      |
|    time_elapsed     | 192      |
|    total_timesteps  | 36288    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.32e-06 |
|    n_updates        | 35287    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 196      |
|    fps              | 188      |
|    time_elapsed     | 196      |
|    total_timesteps  | 37044    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.17e-07 |
|    n_updates        | 36043    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 200      |
|    fps              | 188      |
|    time_elapsed     | 200      |
|    total_timesteps  | 37800    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 8.88e-08 |
|    n_updates        | 36799    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 204      |
|    fps              | 188      |
|    time_elapsed     | 204      |
|    total_timesteps  | 38556    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.47e-06 |
|    n_updates        | 37555    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 208      |
|    fps              | 188      |
|    time_elapsed     | 208      |
|    total_timesteps  | 39312    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.36e-07 |
|    n_updates        | 38311    |
----------------------------------

Validation at step 40000: reward=-0.2145

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 212      |
|    fps              | 189      |
|    time_elapsed     | 211      |
|    total_timesteps  | 40068    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.93e-05 |
|    n_updates        | 39067    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 216      |
|    fps              | 189      |
|    time_elapsed     | 215      |
|    total_timesteps  | 40824    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.09e-07 |
|    n_updates        | 39823    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 220      |
|    fps              | 188      |
|    time_elapsed     | 220      |
|    total_timesteps  | 41580    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.02e-07 |
|    n_updates        | 40579    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 224      |
|    fps              | 188      |
|    time_elapsed     | 224      |
|    total_timesteps  | 42336    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.38e-06 |
|    n_updates        | 41335    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 228      |
|    fps              | 189      |
|    time_elapsed     | 227      |
|    total_timesteps  | 43092    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.38e-07 |
|    n_updates        | 42091    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 232      |
|    fps              | 189      |
|    time_elapsed     | 231      |
|    total_timesteps  | 43848    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.25e-07 |
|    n_updates        | 42847    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 236      |
|    fps              | 189      |
|    time_elapsed     | 235      |
|    total_timesteps  | 44604    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 8.26e-07 |
|    n_updates        | 43603    |
----------------------------------

Validation at step 45000: reward=-0.1811

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 240      |
|    fps              | 188      |
|    time_elapsed     | 240      |
|    total_timesteps  | 45360    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.23e-07 |
|    n_updates        | 44359    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 244      |
|    fps              | 189      |
|    time_elapsed     | 243      |
|    total_timesteps  | 46116    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.19e-05 |
|    n_updates        | 45115    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 248      |
|    fps              | 189      |
|    time_elapsed     | 247      |
|    total_timesteps  | 46872    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.82e-07 |
|    n_updates        | 45871    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 252      |
|    fps              | 189      |
|    time_elapsed     | 251      |
|    total_timesteps  | 47628    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.79e-07 |
|    n_updates        | 46627    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 256      |
|    fps              | 189      |
|    time_elapsed     | 255      |
|    total_timesteps  | 48384    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.96e-06 |
|    n_updates        | 47383    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 260      |
|    fps              | 189      |
|    time_elapsed     | 259      |
|    total_timesteps  | 49140    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.84e-07 |
|    n_updates        | 48139    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 264      |
|    fps              | 189      |
|    time_elapsed     | 263      |
|    total_timesteps  | 49896    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.45e-07 |
|    n_updates        | 48895    |
----------------------------------

Validation at step 50000: reward=-0.0853

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 268      |
|    fps              | 189      |
|    time_elapsed     | 267      |
|    total_timesteps  | 50652    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 9.46e-07 |
|    n_updates        | 49651    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 272      |
|    fps              | 189      |
|    time_elapsed     | 271      |
|    total_timesteps  | 51408    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.89e-07 |
|    n_updates        | 50407    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 276      |
|    fps              | 189      |
|    time_elapsed     | 275      |
|    total_timesteps  | 52164    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.63e-06 |
|    n_updates        | 51163    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 280      |
|    fps              | 189      |
|    time_elapsed     | 279      |
|    total_timesteps  | 52920    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.25e-07 |
|    n_updates        | 51919    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 284      |
|    fps              | 189      |
|    time_elapsed     | 283      |
|    total_timesteps  | 53676    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.96e-07 |
|    n_updates        | 52675    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 288      |
|    fps              | 189      |
|    time_elapsed     | 287      |
|    total_timesteps  | 54432    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.48e-06 |
|    n_updates        | 53431    |
----------------------------------

Validation at step 55000: reward=-0.1082

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 292      |
|    fps              | 189      |
|    time_elapsed     | 291      |
|    total_timesteps  | 55188    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.19e-07 |
|    n_updates        | 54187    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.97     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 296      |
|    fps              | 188      |
|    time_elapsed     | 296      |
|    total_timesteps  | 55944    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.42e-07 |
|    n_updates        | 54943    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 300      |
|    fps              | 188      |
|    time_elapsed     | 300      |
|    total_timesteps  | 56700    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 9.93e-07 |
|    n_updates        | 55699    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 304      |
|    fps              | 189      |
|    time_elapsed     | 303      |
|    total_timesteps  | 57456    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.42e-07 |
|    n_updates        | 56455    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 308      |
|    fps              | 189      |
|    time_elapsed     | 307      |
|    total_timesteps  | 58212    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.38e-06 |
|    n_updates        | 57211    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 312      |
|    fps              | 189      |
|    time_elapsed     | 311      |
|    total_timesteps  | 58968    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.7e-07  |
|    n_updates        | 57967    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 316      |
|    fps              | 189      |
|    time_elapsed     | 315      |
|    total_timesteps  | 59724    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.45e-07 |
|    n_updates        | 58723    |
----------------------------------

Validation at step 60000: reward=-0.1166

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 320      |
|    fps              | 189      |
|    time_elapsed     | 319      |
|    total_timesteps  | 60480    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.82e-06 |
|    n_updates        | 59479    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 324      |
|    fps              | 189      |
|    time_elapsed     | 323      |
|    total_timesteps  | 61236    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.61e-07 |
|    n_updates        | 60235    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 328      |
|    fps              | 189      |
|    time_elapsed     | 327      |
|    total_timesteps  | 61992    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.82e-07 |
|    n_updates        | 60991    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.93     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 332      |
|    fps              | 189      |
|    time_elapsed     | 331      |
|    total_timesteps  | 62748    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.2e-07  |
|    n_updates        | 61747    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 336      |
|    fps              | 188      |
|    time_elapsed     | 336      |
|    total_timesteps  | 63504    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.26e-07 |
|    n_updates        | 62503    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.93     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 340      |
|    fps              | 188      |
|    time_elapsed     | 340      |
|    total_timesteps  | 64260    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.96e-06 |
|    n_updates        | 63259    |
----------------------------------

Validation at step 65000: reward=-0.2597

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.93     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 344      |
|    fps              | 188      |
|    time_elapsed     | 344      |
|    total_timesteps  | 65016    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.84e-07 |
|    n_updates        | 64015    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 348      |
|    fps              | 188      |
|    time_elapsed     | 348      |
|    total_timesteps  | 65772    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.87e-07 |
|    n_updates        | 64771    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.93     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 352      |
|    fps              | 188      |
|    time_elapsed     | 352      |
|    total_timesteps  | 66528    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 9.23e-07 |
|    n_updates        | 65527    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.93     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 356      |
|    fps              | 188      |
|    time_elapsed     | 357      |
|    total_timesteps  | 67284    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.08e-07 |
|    n_updates        | 66283    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.93     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 360      |
|    fps              | 188      |
|    time_elapsed     | 361      |
|    total_timesteps  | 68040    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.5e-05  |
|    n_updates        | 67039    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.92     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 364      |
|    fps              | 188      |
|    time_elapsed     | 365      |
|    total_timesteps  | 68796    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.53e-06 |
|    n_updates        | 67795    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.93     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 368      |
|    fps              | 188      |
|    time_elapsed     | 369      |
|    total_timesteps  | 69552    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.95e-07 |
|    n_updates        | 68551    |
----------------------------------

Validation at step 70000: reward=-0.1281

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.92     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 372      |
|    fps              | 188      |
|    time_elapsed     | 373      |
|    total_timesteps  | 70308    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.11e-06 |
|    n_updates        | 69307    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.92     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 376      |
|    fps              | 188      |
|    time_elapsed     | 377      |
|    total_timesteps  | 71064    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.7e-07  |
|    n_updates        | 70063    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.93     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 380      |
|    fps              | 188      |
|    time_elapsed     | 381      |
|    total_timesteps  | 71820    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.8e-07  |
|    n_updates        | 70819    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.91     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 384      |
|    fps              | 188      |
|    time_elapsed     | 385      |
|    total_timesteps  | 72576    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 8.99e-07 |
|    n_updates        | 71575    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.92     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 388      |
|    fps              | 188      |
|    time_elapsed     | 389      |
|    total_timesteps  | 73332    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.08e-07 |
|    n_updates        | 72331    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.92     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 392      |
|    fps              | 188      |
|    time_elapsed     | 393      |
|    total_timesteps  | 74088    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 8.63e-06 |
|    n_updates        | 73087    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.91     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 396      |
|    fps              | 188      |
|    time_elapsed     | 397      |
|    total_timesteps  | 74844    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.45e-06 |
|    n_updates        | 73843    |
----------------------------------

Validation at step 75000: reward=-0.1292

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.92     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 400      |
|    fps              | 188      |
|    time_elapsed     | 401      |
|    total_timesteps  | 75600    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.28e-07 |
|    n_updates        | 74599    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.91     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 404      |
|    fps              | 188      |
|    time_elapsed     | 405      |
|    total_timesteps  | 76356    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.62e-06 |
|    n_updates        | 75355    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.91     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 408      |
|    fps              | 188      |
|    time_elapsed     | 409      |
|    total_timesteps  | 77112    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3e-07    |
|    n_updates        | 76111    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.92     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 412      |
|    fps              | 188      |
|    time_elapsed     | 413      |
|    total_timesteps  | 77868    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.46e-07 |
|    n_updates        | 76867    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.92     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 416      |
|    fps              | 188      |
|    time_elapsed     | 417      |
|    total_timesteps  | 78624    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.94e-07 |
|    n_updates        | 77623    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.93     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 420      |
|    fps              | 188      |
|    time_elapsed     | 421      |
|    total_timesteps  | 79380    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.37e-07 |
|    n_updates        | 78379    |
----------------------------------

Validation at step 80000: reward=-0.1570

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.93     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 424      |
|    fps              | 188      |
|    time_elapsed     | 425      |
|    total_timesteps  | 80136    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.18e-05 |
|    n_updates        | 79135    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.93     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 428      |
|    fps              | 188      |
|    time_elapsed     | 429      |
|    total_timesteps  | 80892    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.65e-07 |
|    n_updates        | 79891    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 432      |
|    fps              | 188      |
|    time_elapsed     | 433      |
|    total_timesteps  | 81648    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.53e-07 |
|    n_updates        | 80647    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 436      |
|    fps              | 188      |
|    time_elapsed     | 437      |
|    total_timesteps  | 82404    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.12e-06 |
|    n_updates        | 81403    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 440      |
|    fps              | 188      |
|    time_elapsed     | 441      |
|    total_timesteps  | 83160    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.49e-07 |
|    n_updates        | 82159    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 444      |
|    fps              | 188      |
|    time_elapsed     | 445      |
|    total_timesteps  | 83916    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.2e-07  |
|    n_updates        | 82915    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 448      |
|    fps              | 188      |
|    time_elapsed     | 449      |
|    total_timesteps  | 84672    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.15e-07 |
|    n_updates        | 83671    |
----------------------------------

Validation at step 85000: reward=-0.1150

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 452      |
|    fps              | 188      |
|    time_elapsed     | 453      |
|    total_timesteps  | 85428    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.65e-07 |
|    n_updates        | 84427    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 456      |
|    fps              | 188      |
|    time_elapsed     | 457      |
|    total_timesteps  | 86184    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.98e-06 |
|    n_updates        | 85183    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 460      |
|    fps              | 188      |
|    time_elapsed     | 461      |
|    total_timesteps  | 86940    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.65e-07 |
|    n_updates        | 85939    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 464      |
|    fps              | 187      |
|    time_elapsed     | 466      |
|    total_timesteps  | 87696    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.55e-07 |
|    n_updates        | 86695    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.94     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 468      |
|    fps              | 187      |
|    time_elapsed     | 471      |
|    total_timesteps  | 88452    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.81e-07 |
|    n_updates        | 87451    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 472      |
|    fps              | 187      |
|    time_elapsed     | 475      |
|    total_timesteps  | 89208    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.27e-07 |
|    n_updates        | 88207    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 476      |
|    fps              | 187      |
|    time_elapsed     | 479      |
|    total_timesteps  | 89964    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.93e-07 |
|    n_updates        | 88963    |
----------------------------------

Validation at step 90000: reward=0.0290

  -> New best validation reward!

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.95     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 480      |
|    fps              | 187      |
|    time_elapsed     | 483      |
|    total_timesteps  | 90720    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.6e-07  |
|    n_updates        | 89719    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 484      |
|    fps              | 187      |
|    time_elapsed     | 488      |
|    total_timesteps  | 91476    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.79e-07 |
|    n_updates        | 90475    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 488      |
|    fps              | 187      |
|    time_elapsed     | 491      |
|    total_timesteps  | 92232    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.58e-06 |
|    n_updates        | 91231    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 492      |
|    fps              | 187      |
|    time_elapsed     | 495      |
|    total_timesteps  | 92988    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.33e-07 |
|    n_updates        | 91987    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.97     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 496      |
|    fps              | 187      |
|    time_elapsed     | 500      |
|    total_timesteps  | 93744    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.13e-07 |
|    n_updates        | 92743    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 500      |
|    fps              | 187      |
|    time_elapsed     | 504      |
|    total_timesteps  | 94500    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.13e-07 |
|    n_updates        | 93499    |
----------------------------------

Validation at step 95000: reward=-0.0442

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 504      |
|    fps              | 187      |
|    time_elapsed     | 508      |
|    total_timesteps  | 95256    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.93e-07 |
|    n_updates        | 94255    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.97     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 508      |
|    fps              | 187      |
|    time_elapsed     | 512      |
|    total_timesteps  | 96012    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 0.000319 |
|    n_updates        | 95011    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 512      |
|    fps              | 187      |
|    time_elapsed     | 516      |
|    total_timesteps  | 96768    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.19e-07 |
|    n_updates        | 95767    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 516      |
|    fps              | 187      |
|    time_elapsed     | 520      |
|    total_timesteps  | 97524    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.34e-07 |
|    n_updates        | 96523    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 520      |
|    fps              | 187      |
|    time_elapsed     | 524      |
|    total_timesteps  | 98280    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.6e-06  |
|    n_updates        | 97279    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 524      |
|    fps              | 187      |
|    time_elapsed     | 528      |
|    total_timesteps  | 99036    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.76e-07 |
|    n_updates        | 98035    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 528      |
|    fps              | 187      |
|    time_elapsed     | 532      |
|    total_timesteps  | 99792    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.34e-07 |
|    n_updates        | 98791    |
----------------------------------

Validation at step 100000: reward=-0.1072

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 189      |
|    ep_rew_mean        | 0.267    |
| time/                 |          |
|    fps                | 285      |
|    iterations         | 100      |
|    time_elapsed       | 89       |
|    total_timesteps    | 25600    |
| train/                |          |
|    entropy_loss       | -1.94    |
|    explained_variance | 0.87     |
|    learning_rate      | 0.0005   |
|    n_updates          | 99       |
|    policy_loss        | 0.135    |
|    value_loss         | 0.0138   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 189      |
|    ep_rew_mean        | 0.42     |
| time/                 |          |
|    fps                | 281      |
|    iterations         | 200      |
|    time_elapsed       | 181      |
|    total_timesteps    | 51200    |
| train/                |          |
|    entropy_loss       | -1.92    |
|    explained_variance | 0.907    |
|    learning_rate      | 0.0005   |
|    n_updates          | 199      |
|    policy_loss        | 0.0336   |
|    value_loss         | 0.00476  |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 189      |
|    ep_rew_mean        | 0.737    |
| time/                 |          |
|    fps                | 279      |
|    iterations         | 300      |
|    time_elapsed       | 274      |
|    total_timesteps    | 76800    |
| train/                |          |
|    entropy_loss       | -1.85    |
|    explained_variance | 0.966    |
|    learning_rate      | 0.0005   |
|    n_updates          | 299      |
|    policy_loss        | 0.00982  |
|    value_loss         | 0.00422  |
------------------------------------

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 189      |
|    ep_rew_mean     | 0.209    |
| time/              |          |
|    fps             | 308      |
|    iterations      | 1        |
|    time_elapsed    | 6        |
|    total_timesteps | 2048     |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 189          |
|    ep_rew_mean          | 0.16         |
| time/                   |              |
|    fps                  | 339          |
|    iterations           | 2            |
|    time_elapsed         | 12           |
|    total_timesteps      | 4096         |
| train/                  |              |
|    approx_kl            | 0.0020428514 |
|    clip_fraction        | 0.000293     |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.95        |
|    explained_variance   | -4.1         |
|    learning_rate        | 0.0003       |
|    loss                 | -0.0354      |
|    n_updates            | 10           |
|    policy_gradient_loss | -0.011       |
|    value_loss           | 0.0549       |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 189          |
|    ep_rew_mean          | 0.159        |
| time/                   |              |
|    fps                  | 361          |
|    iterations           | 3            |
|    time_elapsed         | 16           |
|    total_timesteps      | 6144         |
| train/                  |              |
|    approx_kl            | 0.0023343503 |
|    clip_fraction        | 0.00391      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.94        |
|    explained_variance   | 0.275        |
|    learning_rate        | 0.0003       |
|    loss                 | -0.039       |
|    n_updates            | 20           |
|    policy_gradient_loss | -0.0124      |
|    value_loss           | 0.00635      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 189          |
|    ep_rew_mean          | 0.199        |
| time/                   |              |
|    fps                  | 369          |
|    iterations           | 4            |
|    time_elapsed         | 22           |
|    total_timesteps      | 8192         |
| train/                  |              |
|    approx_kl            | 0.0057422277 |
|    clip_fraction        | 0.0146       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.94        |
|    explained_variance   | 0.62         |
|    learning_rate        | 0.0003       |
|    loss                 | -0.0495      |
|    n_updates            | 30           |
|    policy_gradient_loss | -0.0199      |
|    value_loss           | 0.00364      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 0.225       |
| time/                   |             |
|    fps                  | 368         |
|    iterations           | 5           |
|    time_elapsed         | 27          |
|    total_timesteps      | 10240       |
| train/                  |             |
|    approx_kl            | 0.006076508 |
|    clip_fraction        | 0.0176      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.93       |
|    explained_variance   | 0.809       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0554     |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0209     |
|    value_loss           | 0.0027      |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 0.241       |
| time/                   |             |
|    fps                  | 362         |
|    iterations           | 6           |
|    time_elapsed         | 33          |
|    total_timesteps      | 12288       |
| train/                  |             |
|    approx_kl            | 0.007479702 |
|    clip_fraction        | 0.0291      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.92       |
|    explained_variance   | 0.894       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0596     |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0247     |
|    value_loss           | 0.00235     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 0.281       |
| time/                   |             |
|    fps                  | 351         |
|    iterations           | 7           |
|    time_elapsed         | 40          |
|    total_timesteps      | 14336       |
| train/                  |             |
|    approx_kl            | 0.011313645 |
|    clip_fraction        | 0.0639      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.9        |
|    explained_variance   | 0.932       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0685     |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0309     |
|    value_loss           | 0.002       |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 0.32        |
| time/                   |             |
|    fps                  | 333         |
|    iterations           | 8           |
|    time_elapsed         | 49          |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.013316788 |
|    clip_fraction        | 0.0922      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.87       |
|    explained_variance   | 0.95        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0654     |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.0332     |
|    value_loss           | 0.00158     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 0.368       |
| time/                   |             |
|    fps                  | 337         |
|    iterations           | 9           |
|    time_elapsed         | 54          |
|    total_timesteps      | 18432       |
| train/                  |             |
|    approx_kl            | 0.017701004 |
|    clip_fraction        | 0.141       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.83       |
|    explained_variance   | 0.966       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0853     |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.0401     |
|    value_loss           | 0.00133     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 0.444       |
| time/                   |             |
|    fps                  | 333         |
|    iterations           | 10          |
|    time_elapsed         | 61          |
|    total_timesteps      | 20480       |
| train/                  |             |
|    approx_kl            | 0.019193958 |
|    clip_fraction        | 0.16        |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.79       |
|    explained_variance   | 0.966       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0895     |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.0396     |
|    value_loss           | 0.00164     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 0.555       |
| time/                   |             |
|    fps                  | 319         |
|    iterations           | 11          |
|    time_elapsed         | 70          |
|    total_timesteps      | 22528       |
| train/                  |             |
|    approx_kl            | 0.019736025 |
|    clip_fraction        | 0.172       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.73       |
|    explained_variance   | 0.968       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0729     |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.0398     |
|    value_loss           | 0.00159     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 0.681       |
| time/                   |             |
|    fps                  | 309         |
|    iterations           | 12          |
|    time_elapsed         | 79          |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.020125672 |
|    clip_fraction        | 0.186       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.66       |
|    explained_variance   | 0.973       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0706     |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.042      |
|    value_loss           | 0.00155     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 0.809       |
| time/                   |             |
|    fps                  | 293         |
|    iterations           | 13          |
|    time_elapsed         | 90          |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.019058824 |
|    clip_fraction        | 0.15        |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.59       |
|    explained_variance   | 0.966       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0646     |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.0359     |
|    value_loss           | 0.00201     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 0.965       |
| time/                   |             |
|    fps                  | 286         |
|    iterations           | 14          |
|    time_elapsed         | 99          |
|    total_timesteps      | 28672       |
| train/                  |             |
|    approx_kl            | 0.019207299 |
|    clip_fraction        | 0.152       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.52       |
|    explained_variance   | 0.975       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0606     |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.0372     |
|    value_loss           | 0.00162     |
-----------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 189        |
|    ep_rew_mean          | 1.12       |
| time/                   |            |
|    fps                  | 281        |
|    iterations           | 15         |
|    time_elapsed         | 109        |
|    total_timesteps      | 30720      |
| train/                  |            |
|    approx_kl            | 0.02220581 |
|    clip_fraction        | 0.18       |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.45      |
|    explained_variance   | 0.979      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0693    |
|    n_updates            | 140        |
|    policy_gradient_loss | -0.0398    |
|    value_loss           | 0.00135    |
----------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 189        |
|    ep_rew_mean          | 1.27       |
| time/                   |            |
|    fps                  | 273        |
|    iterations           | 16         |
|    time_elapsed         | 119        |
|    total_timesteps      | 32768      |
| train/                  |            |
|    approx_kl            | 0.02089906 |
|    clip_fraction        | 0.153      |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.37      |
|    explained_variance   | 0.982      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0615    |
|    n_updates            | 150        |
|    policy_gradient_loss | -0.0346    |
|    value_loss           | 0.0012     |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 1.43        |
| time/                   |             |
|    fps                  | 266         |
|    iterations           | 17          |
|    time_elapsed         | 130         |
|    total_timesteps      | 34816       |
| train/                  |             |
|    approx_kl            | 0.018012984 |
|    clip_fraction        | 0.159       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.27       |
|    explained_variance   | 0.99        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0613     |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.0345     |
|    value_loss           | 0.00101     |
-----------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 189        |
|    ep_rew_mean          | 1.6        |
| time/                   |            |
|    fps                  | 261        |
|    iterations           | 18         |
|    time_elapsed         | 141        |
|    total_timesteps      | 36864      |
| train/                  |            |
|    approx_kl            | 0.01818598 |
|    clip_fraction        | 0.157      |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.19      |
|    explained_variance   | 0.993      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0565    |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.0334    |
|    value_loss           | 0.000964   |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 1.74        |
| time/                   |             |
|    fps                  | 257         |
|    iterations           | 19          |
|    time_elapsed         | 150         |
|    total_timesteps      | 38912       |
| train/                  |             |
|    approx_kl            | 0.013777882 |
|    clip_fraction        | 0.135       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.11       |
|    explained_variance   | 0.995       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0513     |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.0287     |
|    value_loss           | 0.000816    |
-----------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 189        |
|    ep_rew_mean          | 1.87       |
| time/                   |            |
|    fps                  | 254        |
|    iterations           | 20         |
|    time_elapsed         | 160        |
|    total_timesteps      | 40960      |
| train/                  |            |
|    approx_kl            | 0.02333736 |
|    clip_fraction        | 0.17       |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.04      |
|    explained_variance   | 0.992      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0626    |
|    n_updates            | 190        |
|    policy_gradient_loss | -0.0328    |
|    value_loss           | 0.000967   |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 1.98        |
| time/                   |             |
|    fps                  | 252         |
|    iterations           | 21          |
|    time_elapsed         | 170         |
|    total_timesteps      | 43008       |
| train/                  |             |
|    approx_kl            | 0.019338824 |
|    clip_fraction        | 0.155       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.97       |
|    explained_variance   | 0.996       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0518     |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.0304     |
|    value_loss           | 0.000592    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 2.09        |
| time/                   |             |
|    fps                  | 249         |
|    iterations           | 22          |
|    time_elapsed         | 180         |
|    total_timesteps      | 45056       |
| train/                  |             |
|    approx_kl            | 0.019558355 |
|    clip_fraction        | 0.157       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.893      |
|    explained_variance   | 0.996       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0493     |
|    n_updates            | 210         |
|    policy_gradient_loss | -0.0318     |
|    value_loss           | 0.000653    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 2.19        |
| time/                   |             |
|    fps                  | 247         |
|    iterations           | 23          |
|    time_elapsed         | 190         |
|    total_timesteps      | 47104       |
| train/                  |             |
|    approx_kl            | 0.017234657 |
|    clip_fraction        | 0.146       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.828      |
|    explained_variance   | 0.998       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0413     |
|    n_updates            | 220         |
|    policy_gradient_loss | -0.0282     |
|    value_loss           | 0.000417    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 189         |
|    ep_rew_mean          | 2.28        |

Checkpoint saved to D:\acer\Documents\College\Year3_2\PAT_REC\Market-Regime-Detection-for-RL-Allocation\output\full_pipeline\100000\attention_dqn_hmm_news_base.pt

   episode    reward  eval_reward
3        4  0.072534     0.072534
4        5  0.334429     0.334429
5        6 -0.048099    -0.048099

          policy                                          status
0            DQN           bootstrapped -> dqn_hmm_news_base.zip
1            A2C           bootstrapped -> a2c_hmm_news_base.zip
2            PPO           bootstrapped -> ppo_hmm_news_base.zip
3  ATTENTION_DQN  bootstrapped -> attention_dqn_hmm_news_base.pt

In [12]:
baseline_rows = []

for policy_name, model in models.items():
    eval_model = AttentionAgentAdapter(model) if policy_name == "ATTENTION_DQN" else model
    val_stats = evaluate_episode(eval_model, val_env, deterministic=True)
    test_stats = evaluate_episode(eval_model, test_env, deterministic=True)

    baseline_rows.append(
        {"phase": "before_finetune", "policy": policy_name, "split": "validation", **val_stats}
    )
    baseline_rows.append(
        {"phase": "before_finetune", "policy": policy_name, "split": "locked_test", **test_stats}
    )

baseline_table = pd.DataFrame(baseline_rows)[
    [
        "phase",
        "policy",
        "split",
        "reward",
        "length",
        "cumulative_return",
        "sharpe_ratio",
        "max_drawdown",
    ]
]
display(baseline_table.sort_values(["policy", "split"]).reset_index(drop=True))

             phase         policy        split    reward  length  cumulative_return  sharpe_ratio  max_drawdown
0  before_finetune            A2C  locked_test  0.207619     167           0.429033      0.843246     -0.191101
1  before_finetune            A2C   validation -0.122229     105          -0.031770      0.001246     -0.217680
2  before_finetune  ATTENTION_DQN  locked_test  0.281391     167           0.551339      1.050514     -0.171867
3  before_finetune  ATTENTION_DQN   validation -0.401253     105          -0.254731     -1.001406     -0.306355
4  before_finetune            DQN  locked_test  0.386325     167           0.728021      1.390706     -0.107795
5  before_finetune            DQN   validation -0.051260     105           0.040889      0.210554     -0.333981
6  before_finetune            PPO  locked_test  0.220606     167           0.484924      0.902489     -0.196136
7  before_finetune            PPO   validation -0.026351     105           0.061524      0.290051     -0.149639

## Fine-Tune All Policies and Re-Evaluate

Each enabled policy is fine-tuned on the train split, then evaluated on validation and locked test.

In [ ]:
finetune_rows = []
finetune_notes = []

for policy_name, model in models.items():
    paths = CHECKPOINTS[policy_name]
    params = POLICY_CONFIGS[policy_name]

    if policy_name == "DQN":
        model.set_env(train_env)
        model.learn(
            total_timesteps=int(params["finetune_timesteps"]),
            reset_num_timesteps=False,
            progress_bar=True,
        )
        model.save(paths["finetuned"])
    elif policy_name == "A2C":
        model.set_env(train_env)
        model.learn(
            total_timesteps=int(params["finetune_timesteps"]),
            reset_num_timesteps=False,
            progress_bar=True,
        )
        model.save(paths["finetuned"])
    elif policy_name == "PPO":
        model.set_env(train_env)
        model.learn(
            total_timesteps=int(params["finetune_timesteps"]),
            reset_num_timesteps=False,
            progress_bar=True,
        )
        model.save(paths["finetuned"])
    elif policy_name == "ATTENTION_DQN":
        hist = train_attention_dqn(
            model,
            train_env,
            episodes=int(params["finetune_episodes"]),
        )
        model.save_checkpoint(str(paths["finetuned"]))
        display(hist.tail(3))

    finetune_notes.append(
        {"policy": policy_name, "saved": str(paths["finetuned"].relative_to(REPO_ROOT))}
    )

    eval_model = AttentionAgentAdapter(model) if policy_name == "ATTENTION_DQN" else model
    val_stats = evaluate_episode(eval_model, val_env, deterministic=True)
    test_stats = evaluate_episode(eval_model, test_env, deterministic=True)

    finetune_rows.append(
        {"phase": "after_finetune", "policy": policy_name, "split": "validation", **val_stats}
    )
    finetune_rows.append(
        {"phase": "after_finetune", "policy": policy_name, "split": "locked_test", **test_stats}
    )

finetuned_table = pd.DataFrame(finetune_rows)[
    [
        "phase",
        "policy",
        "split",
        "reward",
        "length",
        "cumulative_return",
        "sharpe_ratio",
        "max_drawdown",
    ]
]
comparison = pd.concat([baseline_table, finetuned_table], ignore_index=True)

display(pd.DataFrame(finetune_notes))
display(finetuned_table.sort_values(["policy", "split"]).reset_index(drop=True))
display(comparison.sort_values(["policy", "phase", "split"]).reset_index(drop=True))

# Model comparison summary: rank policies by split and an overall weighted score.
score_table = finetuned_table.groupby(["policy", "split"], as_index=False)[
    ["sharpe_ratio", "cumulative_return", "reward", "max_drawdown"]
].mean()
score_table["score"] = (
    0.45 * score_table["sharpe_ratio"]
    + 0.35 * score_table["cumulative_return"]
    + 0.10 * score_table["reward"]
    + 0.10 * score_table["max_drawdown"]
)

best_by_split = (
    score_table.sort_values(["split", "score"], ascending=[True, False])
    .groupby("split", as_index=False)
    .first()
    .sort_values("split")
    .reset_index(drop=True)
)

best_policy_validation = str(
    best_by_split.loc[best_by_split["split"] == "validation", "policy"].iloc[0]
)
best_policy_locked_test = str(
    best_by_split.loc[best_by_split["split"] == "locked_test", "policy"].iloc[0]
)

print("Best model by split (weighted score):")
display(best_by_split)

print(f"Best validation model: {best_policy_validation}")
print(f"Best locked-test model: {best_policy_locked_test}")

# Matplotlib view of weighted policy scores by split.
splits = list(score_table["split"].dropna().unique())
fig, axes = plt.subplots(1, len(splits), figsize=(7 * max(1, len(splits)), 4), squeeze=False)

for idx, split_name in enumerate(splits):
    ax = axes[0, idx]
    split_scores = score_table.loc[score_table["split"] == split_name].sort_values("score", ascending=False)
    ax.bar(split_scores["policy"], split_scores["score"], color="steelblue")
    ax.set_title(f"Policy score - {split_name}")
    ax.set_ylabel("Weighted score")
    ax.set_xlabel("Policy")
    ax.tick_params(axis="x", rotation=25)
    ax.grid(axis="y", linestyle="--", alpha=0.35)

fig.tight_layout()
plt.show()

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 532      |
|    fps              | 92       |
|    time_elapsed     | 6        |
|    total_timesteps  | 100567   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.76e-07 |
|    n_updates        | 99566    |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.97     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 536      |
|    fps              | 92       |
|    time_elapsed     | 14       |
|    total_timesteps  | 101323   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.8e-07  |
|    n_updates        | 100322   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.97     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 540      |
|    fps              | 93       |
|    time_elapsed     | 22       |
|    total_timesteps  | 102079   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.82e-06 |
|    n_updates        | 101078   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 544      |
|    fps              | 93       |
|    time_elapsed     | 30       |
|    total_timesteps  | 102835   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.73e-07 |
|    n_updates        | 101834   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.97     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 548      |
|    fps              | 0        |
|    time_elapsed     | 3847     |
|    total_timesteps  | 103591   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.84e-07 |
|    n_updates        | 102590   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.97     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 552      |
|    fps              | 1        |
|    time_elapsed     | 3855     |
|    total_timesteps  | 104347   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.26e-06 |
|    n_updates        | 103346   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.97     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 556      |
|    fps              | 1        |
|    time_elapsed     | 3863     |
|    total_timesteps  | 105103   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.74e-07 |
|    n_updates        | 104102   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.97     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 560      |
|    fps              | 1        |
|    time_elapsed     | 3870     |
|    total_timesteps  | 105859   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.6e-07  |
|    n_updates        | 104858   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 564      |
|    fps              | 1        |
|    time_elapsed     | 3877     |
|    total_timesteps  | 106615   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.59e-07 |
|    n_updates        | 105614   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.97     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 568      |
|    fps              | 1        |
|    time_elapsed     | 3882     |
|    total_timesteps  | 107371   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 8.9e-08  |
|    n_updates        | 106370   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.97     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 572      |
|    fps              | 2        |
|    time_elapsed     | 3887     |
|    total_timesteps  | 108127   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 9.72e-06 |
|    n_updates        | 107126   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.97     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 576      |
|    fps              | 2        |
|    time_elapsed     | 3891     |
|    total_timesteps  | 108883   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.07e-07 |
|    n_updates        | 107882   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.98     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 580      |
|    fps              | 2        |
|    time_elapsed     | 3895     |
|    total_timesteps  | 109639   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.52e-07 |
|    n_updates        | 108638   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.98     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 584      |
|    fps              | 2        |
|    time_elapsed     | 3899     |
|    total_timesteps  | 110395   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 8.97e-07 |
|    n_updates        | 109394   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.98     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 588      |
|    fps              | 2        |
|    time_elapsed     | 3903     |
|    total_timesteps  | 111151   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.98e-07 |
|    n_updates        | 110150   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.99     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 592      |
|    fps              | 3        |
|    time_elapsed     | 3908     |
|    total_timesteps  | 111907   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.27e-07 |
|    n_updates        | 110906   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.99     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 596      |
|    fps              | 3        |
|    time_elapsed     | 3912     |
|    total_timesteps  | 112663   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.73e-07 |
|    n_updates        | 111662   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.99     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 600      |
|    fps              | 3        |
|    time_elapsed     | 3917     |
|    total_timesteps  | 113419   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.82e-07 |
|    n_updates        | 112418   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.99     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 604      |
|    fps              | 3        |
|    time_elapsed     | 3921     |
|    total_timesteps  | 114175   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.25e-06 |
|    n_updates        | 113174   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.99     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 608      |
|    fps              | 3        |
|    time_elapsed     | 3925     |
|    total_timesteps  | 114931   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.94e-07 |
|    n_updates        | 113930   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 3        |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 612      |
|    fps              | 3        |
|    time_elapsed     | 3929     |
|    total_timesteps  | 115687   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.32e-07 |
|    n_updates        | 114686   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.99     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 616      |
|    fps              | 4        |
|    time_elapsed     | 3933     |
|    total_timesteps  | 116443   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.42e-07 |
|    n_updates        | 115442   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.99     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 620      |
|    fps              | 4        |
|    time_elapsed     | 3938     |
|    total_timesteps  | 117199   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.45e-07 |
|    n_updates        | 116198   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 3        |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 624      |
|    fps              | 4        |
|    time_elapsed     | 3942     |
|    total_timesteps  | 117955   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.64e-07 |
|    n_updates        | 116954   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.99     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 628      |
|    fps              | 4        |
|    time_elapsed     | 3947     |
|    total_timesteps  | 118711   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.92e-07 |
|    n_updates        | 117710   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 3        |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 632      |
|    fps              | 4        |
|    time_elapsed     | 3951     |
|    total_timesteps  | 119467   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.58e-07 |
|    n_updates        | 118466   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 3        |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 636      |
|    fps              | 5        |
|    time_elapsed     | 3956     |
|    total_timesteps  | 120223   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.94e-06 |
|    n_updates        | 119222   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.99     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 640      |
|    fps              | 5        |
|    time_elapsed     | 3960     |
|    total_timesteps  | 120979   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.65e-07 |
|    n_updates        | 119978   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 3        |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 644      |
|    fps              | 5        |
|    time_elapsed     | 3964     |
|    total_timesteps  | 121735   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.96e-07 |
|    n_updates        | 120734   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.99     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 648      |
|    fps              | 5        |
|    time_elapsed     | 3969     |
|    total_timesteps  | 122491   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.15e-07 |
|    n_updates        | 121490   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.99     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 652      |
|    fps              | 5        |
|    time_elapsed     | 3973     |
|    total_timesteps  | 123247   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.9e-07  |
|    n_updates        | 122246   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 3        |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 656      |
|    fps              | 6        |
|    time_elapsed     | 3978     |
|    total_timesteps  | 124003   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 0.000786 |
|    n_updates        | 123002   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.99     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 660      |
|    fps              | 6        |
|    time_elapsed     | 3983     |
|    total_timesteps  | 124759   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2e-07    |
|    n_updates        | 123758   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 3        |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 664      |
|    fps              | 6        |
|    time_elapsed     | 3989     |
|    total_timesteps  | 125515   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.6e-07  |
|    n_updates        | 124514   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 3        |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 668      |
|    fps              | 6        |
|    time_elapsed     | 3994     |
|    total_timesteps  | 126271   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.03e-07 |
|    n_updates        | 125270   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 3        |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 672      |
|    fps              | 6        |
|    time_elapsed     | 3998     |
|    total_timesteps  | 127027   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.03e-07 |
|    n_updates        | 126026   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 3        |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 676      |
|    fps              | 6        |
|    time_elapsed     | 4003     |
|    total_timesteps  | 127783   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.51e-07 |
|    n_updates        | 126782   |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 189      |
|    ep_rew_mean      | 2.99     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 680      |
|    fps              | 7        |
|    time_elapsed     | 4008     |
|    total_timesteps  | 128539   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.55e-06 |
|    n_updates        | 127538   |

In [ ]:
validation_export_env = make_rl_env(prepared, split="validation", seq_len=SEQ_LEN, config=EVAL_CONFIG)
locked_test_export_env = make_rl_env(prepared, split="locked_test", seq_len=SEQ_LEN, config=EVAL_CONFIG)

export_rows = []
action_mix_tables = []

for policy_name, model in models.items():
    policy_agent = AttentionAgentAdapter(model) if policy_name == "ATTENTION_DQN" else model
    policy_key = policy_name.lower()

    val_actions = rollout_agent_on_split(policy_agent, validation_export_env, frame, "validation")
    test_actions = rollout_agent_on_split(policy_agent, locked_test_export_env, frame, "locked_test")

    val_path = save_action_frame(
        val_actions,
        RUN_OUTPUT_DIR / f"{policy_key}_validation_actions_finetuned.csv",
    )
    test_path = save_action_frame(
        test_actions,
        RUN_OUTPUT_DIR / f"{policy_key}_locked_test_actions_finetuned.csv",
    )

    export_rows.append(
        {
            "policy": policy_name,
            "validation_actions": str(val_path.relative_to(REPO_ROOT)),
            "locked_test_actions": str(test_path.relative_to(REPO_ROOT)),
        }
    )

    mix = pd.DataFrame(
        {
            "validation": val_actions["action_name"].value_counts(),
            "locked_test": test_actions["action_name"].value_counts(),
        }
    ).fillna(0).astype(int)
    mix["policy"] = policy_name
    action_mix_tables.append(mix.reset_index().rename(columns={"index": "action_name"}))

exports_df = pd.DataFrame(export_rows)
display(exports_df)

action_mix = pd.concat(action_mix_tables, ignore_index=True)
display(action_mix.sort_values(["policy", "action_name"]).reset_index(drop=True))

# Publish canonical aliases using the best validation policy from the comparison cell.
if "best_policy_validation" in globals():
    best_policy = best_policy_validation
else:
    fallback_rank = finetuned_table.loc[finetuned_table["split"] == "validation", ["policy", "sharpe_ratio"]].copy()
    fallback_rank = fallback_rank.sort_values("sharpe_ratio", ascending=False, na_position="last")
    best_policy = str(fallback_rank.iloc[0]["policy"])

best_key = best_policy.lower()
best_val_src = RUN_OUTPUT_DIR / f"{best_key}_validation_actions_finetuned.csv"
best_test_src = RUN_OUTPUT_DIR / f"{best_key}_locked_test_actions_finetuned.csv"
best_val_dst = RUN_OUTPUT_DIR / "rl_validation_actions_finetuned.csv"
best_test_dst = RUN_OUTPUT_DIR / "rl_locked_test_actions_finetuned.csv"
best_val_dst.write_text(best_val_src.read_text(encoding="utf-8"), encoding="utf-8")
best_test_dst.write_text(best_test_src.read_text(encoding="utf-8"), encoding="utf-8")

print(f"Best validation policy (for canonical exports): {best_policy}")
print("Canonical exports:")
print(" ", best_val_dst.relative_to(REPO_ROOT))
print(" ", best_test_dst.relative_to(REPO_ROOT))

          policy                                 validation_actions                                locked_test_actions
0            DQN  output\full_pipeline\100000\dqn_validation_act...  output\full_pipeline\100000\dqn_locked_test_ac...
1            A2C  output\full_pipeline\100000\a2c_validation_act...  output\full_pipeline\100000\a2c_locked_test_ac...
2            PPO  output\full_pipeline\100000\ppo_validation_act...  output\full_pipeline\100000\ppo_locked_test_ac...
3  ATTENTION_DQN  output\full_pipeline\100000\attention_dqn_vali...  output\full_pipeline\100000\attention_dqn_lock...

           action_name  validation  locked_test         policy
0            cash_only           6            9            A2C
1             gld_only           0            7            A2C
2        spy_80_tlt_20           0            5            A2C
3             spy_only          75           85            A2C
4             tlt_only          24           61            A2C
5    balanced_60_30_10           1           14  ATTENTION_DQN
6            cash_only          19           18  ATTENTION_DQN
7             gld_only          43            6  ATTENTION_DQN
8        spy_80_tlt_20           5           35  ATTENTION_DQN
9             spy_only          10           69  ATTENTION_DQN
10            tlt_only          27           25  ATTENTION_DQN
11   balanced_60_30_10          36            5            DQN
12  defensive_20_60_20           6            2            DQN
13            gld_only          29           31            DQN
14       spy_80_tlt_20          28           17            DQN
15            spy_only           4           29            DQN
16            tlt_only           2           83            DQN
17           cash_only          25           19            PPO
18            gld_only          15           23            PPO
19            spy_only          49           77            PPO
20            tlt_only          16           48            PPO

Best validation policy (for canonical exports): ATTENTION_DQN
Canonical exports:
  output\full_pipeline\100000\rl_validation_actions_finetuned.csv
  output\full_pipeline\100000\rl_locked_test_actions_finetuned.csv