# Full Pipeline 04: Fine-Tune Multiple Policies (Including Attention DQN)

This notebook fine-tunes multiple RL policies on the merged full-pipeline state and exports refreshed validation/locked-test actions.

Included policies:
- DQN (SB3)
- A2C (SB3)
- PPO (SB3)
- AttentionDQN (custom agent in ml/agents/dqn_agent.py)

Inputs:
- output/full_pipeline/model_state_weekly_hmm_news.csv
- optional existing checkpoints under output/full_pipeline/ or output/models/

Outputs:
- output/full_pipeline/*_finetuned checkpoints
- output/full_pipeline/*_validation_actions_finetuned.csv
- output/full_pipeline/*_locked_test_actions_finetuned.csv

In [1]:
from pathlib import Path
import contextlib
import io
import random
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from IPython.display import display
from stable_baselines3 import A2C, DQN, PPO

REPO_ROOT = None
for candidate in [Path.cwd(), *Path.cwd().parents]:
    if (candidate / "full_pipeline").exists() and (candidate / "scripts").exists():
        REPO_ROOT = candidate
        break
if REPO_ROOT is None:
    raise RuntimeError("Could not locate the repo root.")

PIPELINE_ROOT = REPO_ROOT / "full_pipeline"
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
if str(PIPELINE_ROOT) not in sys.path:
    sys.path.insert(0, str(PIPELINE_ROOT))

from evaluation import EvaluationConfig
from ml.agents import AttentionDQNAgent
from ml.hyperparameter_config import load_hyperparameter_config
from ml.training_utils import evaluate_episode, train_dqn_finrl
from _pipeline_utils import (
    OUTPUT_DIR,
    build_full_pipeline_artifacts,
    make_rl_env,
    prepare_rl_inputs,
    rollout_agent_on_split,
    save_action_frame,
)

SEED = 42
np.random.seed(SEED)
random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)

pd.set_option("display.max_columns", 220)
pd.set_option("display.width", 220)

In [2]:
# Fine-tuning configuration loaded from shared YAML config
CONFIG_PATH = REPO_ROOT / "configs" / "rl_hyperparameters.yaml"
HP_CONFIG = load_hyperparameter_config(CONFIG_PATH, fast_mode=False)
CFG = HP_CONFIG.values

USE_CUDA = torch.cuda.is_available()
DEVICE = "cuda" if USE_CUDA else "cpu"

if USE_CUDA:
    # RTX 4080-oriented defaults: enable TF32 and cuDNN autotuning for throughput.
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True
    torch.backends.cudnn.benchmark = True

# Reduce noisy stderr logs when state auto-build triggers HMM grid search.
SUPPRESS_HMM_BUILD_STDERR = True

SEQ_LEN = int(CFG["general"]["sequence_length"])
EVAL_CONFIG = EvaluationConfig(
    transaction_cost=float(CFG["environment"]["transaction_cost"]),
    risk_penalty=float(CFG["environment"]["volatility_penalty"]),
    risk_window=int(CFG["environment"]["lookback_vol"]),
)

ENABLED_POLICIES = ["DQN", "A2C", "PPO", "ATTENTION_DQN"]

POLICY_CONFIGS = {
    "DQN": {
        "learning_rate": float(CFG["dqn"]["learning_rate"]),
        "exploration_fraction": float(CFG["dqn"]["exploration_fraction"]),
        "exploration_final_eps": float(CFG["dqn"]["exploration_final_eps"]),
        "target_update_interval": int(CFG["dqn"]["target_update_interval"]),
        "buffer_size": int(CFG["dqn"]["buffer_size"]),
        "batch_size": int(CFG["dqn"]["batch_size"]),
        "gamma": float(CFG["dqn"]["gamma"]),
        "eval_freq": int(CFG["dqn"]["eval_freq"]),
        "early_stopping_patience": int(CFG["dqn"]["early_stopping_patience"]),
        "warmup_timesteps": max(8_000, int(0.12 * int(CFG["dqn"]["train_timesteps"]))),
        "finetune_timesteps": int(CFG["dqn"]["train_timesteps"]),
    },
    "A2C": {
        "learning_rate": float(CFG["a2c"]["learning_rate"]),
        "gamma": float(CFG["a2c"]["gamma"]),
        "n_steps": int(CFG["a2c"]["n_steps"]),
        "ent_coef": float(CFG["a2c"]["ent_coef"]),
        "vf_coef": float(CFG["a2c"]["vf_coef"]),
        "warmup_timesteps": max(8_000, int(0.25 * int(CFG["a2c"]["train_timesteps"]))),
        "finetune_timesteps": int(CFG["a2c"]["train_timesteps"]),
    },
    "PPO": {
        "learning_rate": float(CFG["ppo"]["learning_rate"]),
        "n_steps": int(CFG["ppo"]["n_steps"]),
        "batch_size": int(CFG["ppo"]["batch_size"]),
        "n_epochs": int(CFG["ppo"]["n_epochs"]),
        "gamma": float(CFG["ppo"]["gamma"]),
        "gae_lambda": float(CFG["ppo"]["gae_lambda"]),
        "clip_range": float(CFG["ppo"]["clip_range"]),
        "ent_coef": float(CFG["ppo"]["ent_coef"]),
        "vf_coef": float(CFG["ppo"]["vf_coef"]),
        "warmup_timesteps": max(10_000, int(0.20 * int(CFG["ppo"]["train_timesteps"]))),
        "finetune_timesteps": int(CFG["ppo"]["train_timesteps"]),
    },
    "ATTENTION_DQN": {
        "learning_rate": float(CFG["dqn"]["learning_rate"]),
        "gamma": float(CFG["dqn"]["gamma"]),
        "buffer_capacity": int(CFG["dqn"]["buffer_size"]),
        "batch_size": int(CFG["dqn"]["batch_size"]),
        "target_update_freq": max(250, int(CFG["dqn"]["target_update_interval"] // 4)),
        "epsilon_start": float(CFG["dqn"]["exploration_initial_eps"]),
        "epsilon_end": float(CFG["dqn"]["exploration_final_eps"]),
        "epsilon_decay": 3000,
        "warmup_episodes": 6,
        "finetune_episodes": 10,
    },
}

CHECKPOINTS = {
    "DQN": {
        "base": OUTPUT_DIR / "dqn_hmm_news_base.zip",
        "finetuned": OUTPUT_DIR / "dqn_hmm_news_finetuned.zip",
        "fallback": REPO_ROOT / "output" / "models" / "dqn_finrl_agent.zip",
    },
    "A2C": {
        "base": OUTPUT_DIR / "a2c_hmm_news_base.zip",
        "finetuned": OUTPUT_DIR / "a2c_hmm_news_finetuned.zip",
        "fallback": REPO_ROOT / "output" / "models" / "a2c_finrl_agent.zip",
    },
    "PPO": {
        "base": OUTPUT_DIR / "ppo_hmm_news_base.zip",
        "finetuned": OUTPUT_DIR / "ppo_hmm_news_finetuned.zip",
        "fallback": REPO_ROOT / "output" / "models" / "ppo_finrl_agent.zip",
    },
    "ATTENTION_DQN": {
        "base": OUTPUT_DIR / "attention_dqn_hmm_news_base.pt",
        "finetuned": OUTPUT_DIR / "attention_dqn_hmm_news_finetuned.pt",
        "fallback": REPO_ROOT / "output" / "models" / "attention_dqn_agent.pt",
    },
}

print(f"Hyperparameter config: {CONFIG_PATH.relative_to(REPO_ROOT)}")
print(f"Resolved mode: {'fast' if HP_CONFIG.fast_mode else 'full'}")
print(f"Device: {DEVICE}")
if USE_CUDA:
    print("CUDA GPU:", torch.cuda.get_device_name(0))

print("Enabled policies:", ENABLED_POLICIES)
for policy_name in ENABLED_POLICIES:
    paths = CHECKPOINTS[policy_name]
    print(f"{policy_name} checkpoints:")
    print("  base:", paths["base"].relative_to(REPO_ROOT))
    print("  finetuned:", paths["finetuned"].relative_to(REPO_ROOT))
    print("  fallback:", paths["fallback"].relative_to(REPO_ROOT))

Hyperparameter config: configs/rl_hyperparameters.yaml
Resolved mode: full
Device: cuda
CUDA GPU: NVIDIA GeForce RTX 4080
Enabled policies: ['DQN', 'A2C', 'PPO', 'ATTENTION_DQN']
DQN checkpoints:
  base: output/full_pipeline/dqn_hmm_news_base.zip
  finetuned: output/full_pipeline/dqn_hmm_news_finetuned.zip
  fallback: output/models/dqn_finrl_agent.zip
A2C checkpoints:
  base: output/full_pipeline/a2c_hmm_news_base.zip
  finetuned: output/full_pipeline/a2c_hmm_news_finetuned.zip
  fallback: output/models/a2c_finrl_agent.zip
PPO checkpoints:
  base: output/full_pipeline/ppo_hmm_news_base.zip
  finetuned: output/full_pipeline/ppo_hmm_news_finetuned.zip
  fallback: output/models/ppo_finrl_agent.zip
ATTENTION_DQN checkpoints:
  base: output/full_pipeline/attention_dqn_hmm_news_base.pt
  finetuned: output/full_pipeline/attention_dqn_hmm_news_finetuned.pt
  fallback: output/models/attention_dqn_agent.pt

In [3]:
state_path = OUTPUT_DIR / "model_state_weekly_hmm_news.csv"
if not state_path.exists():
    print(f"Missing pipeline state at {state_path.relative_to(REPO_ROOT)}. Building full pipeline artifacts...")
    if SUPPRESS_HMM_BUILD_STDERR:
        stderr_buffer = io.StringIO()
        with contextlib.redirect_stderr(stderr_buffer):
            artifacts = build_full_pipeline_artifacts()
    else:
        artifacts = build_full_pipeline_artifacts()
    built_state = artifacts["artifact_paths"]["merged_state"]
    print(f"Built pipeline state: {Path(built_state).relative_to(REPO_ROOT)}")
else:
    print(f"Using existing pipeline state: {state_path.relative_to(REPO_ROOT)}")

prepared = prepare_rl_inputs(state_path=state_path)
frame = prepared["frame"]

train_env = make_rl_env(prepared, split="train", seq_len=SEQ_LEN, config=EVAL_CONFIG)
val_env = make_rl_env(prepared, split="validation", seq_len=SEQ_LEN, config=EVAL_CONFIG)
test_env = make_rl_env(prepared, split="locked_test", seq_len=SEQ_LEN, config=EVAL_CONFIG)

state_dim = int(train_env.observation_space.shape[-1])
action_dim = int(train_env.action_space.n)

display(prepared["dataset"].describe_splits())
display(prepared["dataset"].describe_feature_blocks())
print("Feature count:", len(prepared["feature_cols"]))
print("Posterior columns:", prepared["posterior_cols"])
print("State dim:", state_dim)
print("Action dim:", action_dim)

class AttentionAgentAdapter:
    """Adapter that exposes .predict for custom AttentionDQNAgent."""

    def __init__(self, core_agent):
        self.core_agent = core_agent

    def predict(self, obs, deterministic=True):
        action = self.core_agent.select_action(obs, training=not deterministic)
        return np.array([action], dtype=np.int64), None

def train_attention_dqn(agent, env, episodes, deterministic_eval=False):
    history = []
    for ep in range(int(episodes)):
        obs, _ = env.reset()
        done = False
        ep_reward = 0.0

        while not done:
            action = agent.select_action(obs, training=True)
            next_obs, reward, terminated, truncated, _ = env.step(action)
            done = bool(terminated or truncated)
            agent.store_transition(obs, int(action), next_obs, float(reward), done)
            _ = agent.train_step()
            obs = next_obs
            ep_reward += float(reward)

        agent.episode_end()
        eval_reward = float(ep_reward)
        if deterministic_eval:
            eval_reward = float(evaluate_episode(AttentionAgentAdapter(agent), env, deterministic=True)["reward"])
        history.append({"episode": ep + 1, "reward": float(ep_reward), "eval_reward": eval_reward})

    return pd.DataFrame(history)

Using existing pipeline state: output/full_pipeline/model_state_weekly_hmm_news.csv

         split  rows      start        end
0       warmup    14 2014-03-28 2014-06-27
1        train   339 2014-07-04 2020-12-25
2   validation   105 2021-01-01 2022-12-30
3  locked_test   167 2023-01-06 2026-03-13

    block  n_columns                                    example_columns
0   price         35  spy_ret_1d, spy_ret_5d, spy_ret_20d, spy_vol_5...
1   macro         31  bamlh0a0hym2_level, bamlh0a0hym2_chg_5d, cfnai...
2  regime          4  regime_filtered, regime_viterbi, filtered_prob...
3    text          5  news_finbert_compound_spy, news_finbert_compou...

Feature count: 71
Posterior columns: ['filtered_prob_regime_0', 'filtered_prob_regime_1']
State dim: 77
Action dim: 7

## Load Existing Policies or Bootstrap Base Models

If a policy checkpoint is not found, the notebook trains a lightweight warmup model and saves it under output/full_pipeline.

In [4]:
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

models = {}
bootstrap_notes = []

def _try_load_sb3_model(algorithm_cls, candidate_paths, env, device):
    load_errors = []
    for ckpt_path in candidate_paths:
        if not ckpt_path.exists() or ckpt_path.suffix != ".zip":
            continue
        try:
            model = algorithm_cls.load(ckpt_path, env=env, device=device)
            return model, ckpt_path, load_errors
        except ValueError as exc:
            # Most common here: observation/action space mismatch after feature changes.
            load_errors.append(f"{ckpt_path.name}: {exc}")
    return None, None, load_errors

for policy_name in ENABLED_POLICIES:
    paths = CHECKPOINTS[policy_name]
    params = POLICY_CONFIGS[policy_name]
    candidate_paths = [paths["finetuned"], paths["base"], paths["fallback"]]

    if policy_name == "DQN":
        loaded_model, loaded_ckpt, load_errors = _try_load_sb3_model(
            DQN, candidate_paths, train_env, DEVICE
        )
        if loaded_model is not None:
            models[policy_name] = loaded_model
            bootstrap_notes.append({"policy": policy_name, "status": f"loaded {loaded_ckpt.name}"})
        else:
            if load_errors:
                print("Skipping incompatible DQN checkpoint(s):")
                for err in load_errors:
                    print("  -", err)
            warmup = train_dqn_finrl(
                train_env=train_env,
                val_env=val_env,
                total_timesteps=int(params["warmup_timesteps"]),
                eval_freq=int(params["eval_freq"]),
                early_stopping_patience=int(params["early_stopping_patience"]),
                learning_rate=float(params["learning_rate"]),
                exploration_fraction=float(params["exploration_fraction"]),
                exploration_final_eps=float(params["exploration_final_eps"]),
                target_update_interval=int(params["target_update_interval"]),
                buffer_size=int(params["buffer_size"]),
                batch_size=int(params["batch_size"]),
                device=DEVICE,
                verbose=1,
            )
            models[policy_name] = warmup["agent"]
            models[policy_name].save(paths["base"])
            bootstrap_notes.append({"policy": policy_name, "status": f"bootstrapped -> {paths['base'].name}"})

    elif policy_name == "A2C":
        loaded_model, loaded_ckpt, load_errors = _try_load_sb3_model(
            A2C, candidate_paths, train_env, DEVICE
        )
        if loaded_model is not None:
            models[policy_name] = loaded_model
            bootstrap_notes.append({"policy": policy_name, "status": f"loaded {loaded_ckpt.name}"})
        else:
            if load_errors:
                print("Skipping incompatible A2C checkpoint(s):")
                for err in load_errors:
                    print("  -", err)
            model = A2C(
                "MlpPolicy",
                train_env,
                learning_rate=float(params["learning_rate"]),
                gamma=float(params["gamma"]),
                n_steps=int(params["n_steps"]),
                ent_coef=float(params["ent_coef"]),
                vf_coef=float(params["vf_coef"]),
                verbose=1,
                device=DEVICE,
            )
            model.learn(total_timesteps=int(params["warmup_timesteps"]), progress_bar=True)
            model.save(paths["base"])
            models[policy_name] = model
            bootstrap_notes.append({"policy": policy_name, "status": f"bootstrapped -> {paths['base'].name}"})

    elif policy_name == "PPO":
        loaded_model, loaded_ckpt, load_errors = _try_load_sb3_model(
            PPO, candidate_paths, train_env, DEVICE
        )
        if loaded_model is not None:
            models[policy_name] = loaded_model
            bootstrap_notes.append({"policy": policy_name, "status": f"loaded {loaded_ckpt.name}"})
        else:
            if load_errors:
                print("Skipping incompatible PPO checkpoint(s):")
                for err in load_errors:
                    print("  -", err)
            model = PPO(
                "MlpPolicy",
                train_env,
                learning_rate=float(params["learning_rate"]),
                n_steps=int(params["n_steps"]),
                batch_size=int(params["batch_size"]),
                n_epochs=int(params["n_epochs"]),
                gamma=float(params["gamma"]),
                gae_lambda=float(params["gae_lambda"]),
                clip_range=float(params["clip_range"]),
                ent_coef=float(params["ent_coef"]),
                vf_coef=float(params["vf_coef"]),
                verbose=1,
                device=DEVICE,
            )
            model.learn(total_timesteps=int(params["warmup_timesteps"]), progress_bar=True)
            model.save(paths["base"])
            models[policy_name] = model
            bootstrap_notes.append({"policy": policy_name, "status": f"bootstrapped -> {paths['base'].name}"})

    elif policy_name == "ATTENTION_DQN":
        attn_agent = AttentionDQNAgent(
            state_dim=state_dim,
            action_dim=action_dim,
            seq_len=SEQ_LEN,
            learning_rate=float(params["learning_rate"]),
            gamma=float(params["gamma"]),
            epsilon_start=float(params["epsilon_start"]),
            epsilon_end=float(params["epsilon_end"]),
            epsilon_decay=int(params["epsilon_decay"]),
            buffer_capacity=int(params["buffer_capacity"]),
            batch_size=int(params["batch_size"]),
            target_update_freq=int(params["target_update_freq"]),
            use_dueling=True,
            device=DEVICE,
        )
        loaded_attention = False
        for ckpt_path in candidate_paths:
            if not ckpt_path.exists() or ckpt_path.suffix != ".pt":
                continue
            try:
                attn_agent.load_checkpoint(str(ckpt_path))
                bootstrap_notes.append({"policy": policy_name, "status": f"loaded {ckpt_path.name}"})
                loaded_attention = True
                break
            except Exception as exc:
                print(f"Skipping incompatible ATTENTION_DQN checkpoint {ckpt_path.name}: {exc}")

        if not loaded_attention:
            warmup_hist = train_attention_dqn(
                attn_agent,
                train_env,
                episodes=int(params["warmup_episodes"]),
            )
            attn_agent.save_checkpoint(str(paths["base"]))
            bootstrap_notes.append({"policy": policy_name, "status": f"bootstrapped -> {paths['base'].name}"})
            display(warmup_hist.tail(3))

        models[policy_name] = attn_agent

bootstrap_df = pd.DataFrame(bootstrap_notes)
display(bootstrap_df)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Checkpoint loaded from /home/yuaylong/Market-Regime-Detection-for-RL-Allocation/output/full_pipeline/attention_dqn_hmm_news_base.pt

          policy                                 status
0            DQN           loaded dqn_hmm_news_base.zip
1            A2C           loaded a2c_hmm_news_base.zip
2            PPO           loaded ppo_hmm_news_base.zip
3  ATTENTION_DQN  loaded attention_dqn_hmm_news_base.pt

In [5]:
baseline_rows = []

for policy_name, model in models.items():
    eval_model = AttentionAgentAdapter(model) if policy_name == "ATTENTION_DQN" else model
    val_stats = evaluate_episode(eval_model, val_env, deterministic=True)
    test_stats = evaluate_episode(eval_model, test_env, deterministic=True)

    baseline_rows.append(
        {"phase": "before_finetune", "policy": policy_name, "split": "validation", **val_stats}
    )
    baseline_rows.append(
        {"phase": "before_finetune", "policy": policy_name, "split": "locked_test", **test_stats}
    )

baseline_table = pd.DataFrame(baseline_rows)[
    [
        "phase",
        "policy",
        "split",
        "reward",
        "length",
        "cumulative_return",
        "sharpe_ratio",
        "max_drawdown",
    ]
]
display(baseline_table.sort_values(["policy", "split"]).reset_index(drop=True))

             phase         policy        split    reward  length  cumulative_return  sharpe_ratio  max_drawdown
0  before_finetune            A2C  locked_test  0.552134     167           1.032607      1.517423     -0.086501
1  before_finetune            A2C   validation -0.266465     105          -0.153622     -0.554153     -0.374713
2  before_finetune  ATTENTION_DQN  locked_test  0.379850     167           0.712644      1.149680     -0.132128
3  before_finetune  ATTENTION_DQN   validation -0.132505     105          -0.028874     -0.014815     -0.273911
4  before_finetune            DQN  locked_test  0.441423     167           0.793867      1.431071     -0.137661
5  before_finetune            DQN   validation -0.200696     105          -0.093730     -0.235129     -0.240352
6  before_finetune            PPO  locked_test -0.101982     167           0.054234      0.195594     -0.180338
7  before_finetune            PPO   validation -0.250780     105          -0.135097     -0.359375     -0.347143

## Fine-Tune All Policies and Re-Evaluate

Each enabled policy is fine-tuned on the train split, then evaluated on validation and locked test.

In [ ]:
finetune_rows = []
finetune_notes = []

for policy_name, model in models.items():
    paths = CHECKPOINTS[policy_name]
    params = POLICY_CONFIGS[policy_name]

    if policy_name == "DQN":
        model.set_env(train_env)
        model.learn(
            total_timesteps=int(params["finetune_timesteps"]),
            reset_num_timesteps=False,
            progress_bar=True,
        )
        model.save(paths["finetuned"])
    elif policy_name == "A2C":
        model.set_env(train_env)
        model.learn(
            total_timesteps=int(params["finetune_timesteps"]),
            reset_num_timesteps=False,
            progress_bar=True,
        )
        model.save(paths["finetuned"])
    elif policy_name == "PPO":
        model.set_env(train_env)
        model.learn(
            total_timesteps=int(params["finetune_timesteps"]),
            reset_num_timesteps=False,
            progress_bar=True,
        )
        model.save(paths["finetuned"])
    elif policy_name == "ATTENTION_DQN":
        hist = train_attention_dqn(
            model,
            train_env,
            episodes=int(params["finetune_episodes"]),
        )
        model.save_checkpoint(str(paths["finetuned"]))
        display(hist.tail(3))

    finetune_notes.append(
        {"policy": policy_name, "saved": str(paths["finetuned"].relative_to(REPO_ROOT))}
    )

    eval_model = AttentionAgentAdapter(model) if policy_name == "ATTENTION_DQN" else model
    val_stats = evaluate_episode(eval_model, val_env, deterministic=True)
    test_stats = evaluate_episode(eval_model, test_env, deterministic=True)

    finetune_rows.append(
        {"phase": "after_finetune", "policy": policy_name, "split": "validation", **val_stats}
    )
    finetune_rows.append(
        {"phase": "after_finetune", "policy": policy_name, "split": "locked_test", **test_stats}
    )

finetuned_table = pd.DataFrame(finetune_rows)[
    [
        "phase",
        "policy",
        "split",
        "reward",
        "length",
        "cumulative_return",
        "sharpe_ratio",
        "max_drawdown",
    ]
]
comparison = pd.concat([baseline_table, finetuned_table], ignore_index=True)

display(pd.DataFrame(finetune_notes))
display(finetuned_table.sort_values(["policy", "split"]).reset_index(drop=True))
display(comparison.sort_values(["policy", "phase", "split"]).reset_index(drop=True))

# Model comparison summary: rank policies by split and an overall weighted score.
score_table = finetuned_table.groupby(["policy", "split"], as_index=False)[
    ["sharpe_ratio", "cumulative_return", "reward", "max_drawdown"]
].mean()
score_table["score"] = (
    0.45 * score_table["sharpe_ratio"]
    + 0.35 * score_table["cumulative_return"]
    + 0.10 * score_table["reward"]
    + 0.10 * score_table["max_drawdown"]
)

best_by_split = (
    score_table.sort_values(["split", "score"], ascending=[True, False])
    .groupby("split", as_index=False)
    .first()
    .sort_values("split")
    .reset_index(drop=True)
)

best_policy_validation = str(
    best_by_split.loc[best_by_split["split"] == "validation", "policy"].iloc[0]
)
best_policy_locked_test = str(
    best_by_split.loc[best_by_split["split"] == "locked_test", "policy"].iloc[0]
)

print("Best model by split (weighted score):")
display(best_by_split)

print(f"Best validation model: {best_policy_validation}")
print(f"Best locked-test model: {best_policy_locked_test}")

# Matplotlib view of weighted policy scores by split.
splits = list(score_table["split"].dropna().unique())
fig, axes = plt.subplots(1, len(splits), figsize=(7 * max(1, len(splits)), 4), squeeze=False)

for idx, split_name in enumerate(splits):
    ax = axes[0, idx]
    split_scores = score_table.loc[score_table["split"] == split_name].sort_values("score", ascending=False)
    ax.bar(split_scores["policy"], split_scores["score"], color="steelblue")
    ax.set_title(f"Policy score - {split_name}")
    ax.set_ylabel("Weighted score")
    ax.set_xlabel("Policy")
    ax.tick_params(axis="x", rotation=25)
    ax.grid(axis="y", linestyle="--", alpha=0.35)

fig.tight_layout()
plt.show()

Output()

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.5      |
|    exploration_rate | 0.309    |
| time/               |          |
|    episodes         | 108      |
|    fps              | 336      |
|    time_elapsed     | 2        |
|    total_timesteps  | 36678    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 8.25e-06 |
|    n_updates        | 35677    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.56     |
|    exploration_rate | 0.283    |
| time/               |          |
|    episodes         | 112      |
|    fps              | 350      |
|    time_elapsed     | 5        |
|    total_timesteps  | 38034    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 0.000218 |
|    n_updates        | 37033    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.56     |
|    exploration_rate | 0.258    |
| time/               |          |
|    episodes         | 116      |
|    fps              | 321      |
|    time_elapsed     | 10       |
|    total_timesteps  | 39390    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.07e-06 |
|    n_updates        | 38389    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.55     |
|    exploration_rate | 0.232    |
| time/               |          |
|    episodes         | 120      |
|    fps              | 316      |
|    time_elapsed     | 14       |
|    total_timesteps  | 40746    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.71e-06 |
|    n_updates        | 39745    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.53     |
|    exploration_rate | 0.206    |
| time/               |          |
|    episodes         | 124      |
|    fps              | 313      |
|    time_elapsed     | 19       |
|    total_timesteps  | 42102    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.65e-05 |
|    n_updates        | 41101    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.51     |
|    exploration_rate | 0.181    |
| time/               |          |
|    episodes         | 128      |
|    fps              | 316      |
|    time_elapsed     | 23       |
|    total_timesteps  | 43458    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.07e-06 |
|    n_updates        | 42457    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.5      |
|    exploration_rate | 0.155    |
| time/               |          |
|    episodes         | 132      |
|    fps              | 314      |
|    time_elapsed     | 28       |
|    total_timesteps  | 44814    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.18e-06 |
|    n_updates        | 43813    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.49     |
|    exploration_rate | 0.13     |
| time/               |          |
|    episodes         | 136      |
|    fps              | 316      |
|    time_elapsed     | 32       |
|    total_timesteps  | 46170    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.12e-05 |
|    n_updates        | 45169    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.49     |
|    exploration_rate | 0.104    |
| time/               |          |
|    episodes         | 140      |
|    fps              | 313      |
|    time_elapsed     | 36       |
|    total_timesteps  | 47526    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.63e-06 |
|    n_updates        | 46525    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.49     |
|    exploration_rate | 0.0786   |
| time/               |          |
|    episodes         | 144      |
|    fps              | 310      |
|    time_elapsed     | 41       |
|    total_timesteps  | 48882    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.92e-06 |
|    n_updates        | 47881    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.5      |
|    exploration_rate | 0.0531   |
| time/               |          |
|    episodes         | 148      |
|    fps              | 309      |
|    time_elapsed     | 45       |
|    total_timesteps  | 50238    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.08e-06 |
|    n_updates        | 49237    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.51     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 152      |
|    fps              | 304      |
|    time_elapsed     | 51       |
|    total_timesteps  | 51594    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.83e-07 |
|    n_updates        | 50593    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.52     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 156      |
|    fps              | 301      |
|    time_elapsed     | 56       |
|    total_timesteps  | 52950    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.2e-06  |
|    n_updates        | 51949    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.53     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 160      |
|    fps              | 301      |
|    time_elapsed     | 60       |
|    total_timesteps  | 54306    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.35e-06 |
|    n_updates        | 53305    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.53     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 164      |
|    fps              | 298      |
|    time_elapsed     | 65       |
|    total_timesteps  | 55662    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.07e-06 |
|    n_updates        | 54661    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.54     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 168      |
|    fps              | 296      |
|    time_elapsed     | 70       |
|    total_timesteps  | 57018    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.1e-06  |
|    n_updates        | 56017    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.55     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 172      |
|    fps              | 297      |
|    time_elapsed     | 75       |
|    total_timesteps  | 58374    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.37e-06 |
|    n_updates        | 57373    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.56     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 176      |
|    fps              | 296      |
|    time_elapsed     | 79       |
|    total_timesteps  | 59730    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.46e-07 |
|    n_updates        | 58729    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.57     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 180      |
|    fps              | 296      |
|    time_elapsed     | 84       |
|    total_timesteps  | 61086    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.03e-06 |
|    n_updates        | 60085    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.57     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 184      |
|    fps              | 294      |
|    time_elapsed     | 89       |
|    total_timesteps  | 62442    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.11e-06 |
|    n_updates        | 61441    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.58     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 188      |
|    fps              | 291      |
|    time_elapsed     | 95       |
|    total_timesteps  | 63798    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.35e-07 |
|    n_updates        | 62797    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.59     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 192      |
|    fps              | 290      |
|    time_elapsed     | 100      |
|    total_timesteps  | 65154    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.03e-06 |
|    n_updates        | 64153    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.6      |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 196      |
|    fps              | 289      |
|    time_elapsed     | 105      |
|    total_timesteps  | 66510    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.46e-06 |
|    n_updates        | 65509    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.61     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 200      |
|    fps              | 289      |
|    time_elapsed     | 110      |
|    total_timesteps  | 67866    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.26e-06 |
|    n_updates        | 66865    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.62     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 204      |
|    fps              | 289      |
|    time_elapsed     | 114      |
|    total_timesteps  | 69222    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 8.93e-07 |
|    n_updates        | 68221    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.68     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 208      |
|    fps              | 288      |
|    time_elapsed     | 119      |
|    total_timesteps  | 70578    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.3e-06  |
|    n_updates        | 69577    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.75     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 212      |
|    fps              | 289      |
|    time_elapsed     | 124      |
|    total_timesteps  | 71934    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.83e-07 |
|    n_updates        | 70933    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.81     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 216      |
|    fps              | 289      |
|    time_elapsed     | 128      |
|    total_timesteps  | 73290    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.99e-07 |
|    n_updates        | 72289    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.85     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 220      |
|    fps              | 289      |
|    time_elapsed     | 133      |
|    total_timesteps  | 74646    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.1e-06  |
|    n_updates        | 73645    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.9      |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 224      |
|    fps              | 289      |
|    time_elapsed     | 138      |
|    total_timesteps  | 76002    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 0.000691 |
|    n_updates        | 75001    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.93     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 228      |
|    fps              | 289      |
|    time_elapsed     | 142      |
|    total_timesteps  | 77358    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.54e-07 |
|    n_updates        | 76357    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.96     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 232      |
|    fps              | 289      |
|    time_elapsed     | 147      |
|    total_timesteps  | 78714    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 9.69e-07 |
|    n_updates        | 77713    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 4.98     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 236      |
|    fps              | 290      |
|    time_elapsed     | 151      |
|    total_timesteps  | 80070    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.59e-05 |
|    n_updates        | 79069    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5        |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 240      |
|    fps              | 291      |
|    time_elapsed     | 156      |
|    total_timesteps  | 81426    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.75e-07 |
|    n_updates        | 80425    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.02     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 244      |
|    fps              | 292      |
|    time_elapsed     | 160      |
|    total_timesteps  | 82782    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.68e-07 |
|    n_updates        | 81781    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.02     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 248      |
|    fps              | 291      |
|    time_elapsed     | 164      |
|    total_timesteps  | 84138    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.48e-06 |
|    n_updates        | 83137    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.03     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 252      |
|    fps              | 292      |
|    time_elapsed     | 169      |
|    total_timesteps  | 85494    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.26e-07 |
|    n_updates        | 84493    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.03     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 256      |
|    fps              | 292      |
|    time_elapsed     | 174      |
|    total_timesteps  | 86850    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.25e-07 |
|    n_updates        | 85849    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.03     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 260      |
|    fps              | 291      |
|    time_elapsed     | 178      |
|    total_timesteps  | 88206    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.83e-06 |
|    n_updates        | 87205    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.03     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 264      |
|    fps              | 291      |
|    time_elapsed     | 183      |
|    total_timesteps  | 89562    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.91e-07 |
|    n_updates        | 88561    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.04     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 268      |
|    fps              | 291      |
|    time_elapsed     | 188      |
|    total_timesteps  | 90918    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 8.06e-07 |
|    n_updates        | 89917    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.04     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 272      |
|    fps              | 291      |
|    time_elapsed     | 192      |
|    total_timesteps  | 92274    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.14e-06 |
|    n_updates        | 91273    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.04     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 276      |
|    fps              | 291      |
|    time_elapsed     | 197      |
|    total_timesteps  | 93630    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.82e-07 |
|    n_updates        | 92629    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.05     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 280      |
|    fps              | 292      |
|    time_elapsed     | 201      |
|    total_timesteps  | 94986    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 8.93e-07 |
|    n_updates        | 93985    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.05     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 284      |
|    fps              | 292      |
|    time_elapsed     | 206      |
|    total_timesteps  | 96342    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.83e-06 |
|    n_updates        | 95341    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.05     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 288      |
|    fps              | 292      |
|    time_elapsed     | 211      |
|    total_timesteps  | 97698    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.03e-06 |
|    n_updates        | 96697    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.06     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 292      |
|    fps              | 292      |
|    time_elapsed     | 215      |
|    total_timesteps  | 99054    |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 9.25e-07 |
|    n_updates        | 98053    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.06     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 296      |
|    fps              | 292      |
|    time_elapsed     | 220      |
|    total_timesteps  | 100410   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.1e-06  |
|    n_updates        | 99409    |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.06     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 300      |
|    fps              | 292      |
|    time_elapsed     | 225      |
|    total_timesteps  | 101766   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.95e-07 |
|    n_updates        | 100765   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.06     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 304      |
|    fps              | 292      |
|    time_elapsed     | 229      |
|    total_timesteps  | 103122   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.86e-07 |
|    n_updates        | 102121   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.06     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 308      |
|    fps              | 292      |
|    time_elapsed     | 234      |
|    total_timesteps  | 104478   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.06e-06 |
|    n_updates        | 103477   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.06     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 312      |
|    fps              | 292      |
|    time_elapsed     | 238      |
|    total_timesteps  | 105834   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.63e-07 |
|    n_updates        | 104833   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.06     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 316      |
|    fps              | 293      |
|    time_elapsed     | 242      |
|    total_timesteps  | 107190   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.6e-07  |
|    n_updates        | 106189   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.06     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 320      |
|    fps              | 291      |
|    time_elapsed     | 248      |
|    total_timesteps  | 108546   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.6e-07  |
|    n_updates        | 107545   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.06     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 324      |
|    fps              | 291      |
|    time_elapsed     | 253      |
|    total_timesteps  | 109902   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.29e-07 |
|    n_updates        | 108901   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.07     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 328      |
|    fps              | 290      |
|    time_elapsed     | 259      |
|    total_timesteps  | 111258   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.19e-07 |
|    n_updates        | 110257   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.07     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 332      |
|    fps              | 289      |
|    time_elapsed     | 264      |
|    total_timesteps  | 112614   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.82e-07 |
|    n_updates        | 111613   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.07     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 336      |
|    fps              | 289      |
|    time_elapsed     | 269      |
|    total_timesteps  | 113970   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.41e-07 |
|    n_updates        | 112969   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.07     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 340      |
|    fps              | 289      |
|    time_elapsed     | 273      |
|    total_timesteps  | 115326   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.27e-07 |
|    n_updates        | 114325   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.08     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 344      |
|    fps              | 289      |
|    time_elapsed     | 278      |
|    total_timesteps  | 116682   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 9.94e-07 |
|    n_updates        | 115681   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.08     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 348      |
|    fps              | 289      |
|    time_elapsed     | 283      |
|    total_timesteps  | 118038   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.78e-05 |
|    n_updates        | 117037   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.08     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 352      |
|    fps              | 289      |
|    time_elapsed     | 288      |
|    total_timesteps  | 119394   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.6e-07  |
|    n_updates        | 118393   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.08     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 356      |
|    fps              | 289      |
|    time_elapsed     | 292      |
|    total_timesteps  | 120750   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.02e-07 |
|    n_updates        | 119749   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.08     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 360      |
|    fps              | 288      |
|    time_elapsed     | 298      |
|    total_timesteps  | 122106   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.03e-06 |
|    n_updates        | 121105   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.09     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 364      |
|    fps              | 288      |
|    time_elapsed     | 302      |
|    total_timesteps  | 123462   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.99e-07 |
|    n_updates        | 122461   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.08     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 368      |
|    fps              | 288      |
|    time_elapsed     | 307      |
|    total_timesteps  | 124818   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.82e-07 |
|    n_updates        | 123817   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.09     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 372      |
|    fps              | 289      |
|    time_elapsed     | 311      |
|    total_timesteps  | 126174   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.73e-06 |
|    n_updates        | 125173   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.08     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 376      |
|    fps              | 289      |
|    time_elapsed     | 315      |
|    total_timesteps  | 127530   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.13e-07 |
|    n_updates        | 126529   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.08     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 380      |
|    fps              | 289      |
|    time_elapsed     | 320      |
|    total_timesteps  | 128886   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.22e-07 |
|    n_updates        | 127885   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.09     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 384      |
|    fps              | 289      |
|    time_elapsed     | 325      |
|    total_timesteps  | 130242   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.14e-06 |
|    n_updates        | 129241   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.08     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 388      |
|    fps              | 290      |
|    time_elapsed     | 329      |
|    total_timesteps  | 131598   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.53e-07 |
|    n_updates        | 130597   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.09     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 392      |
|    fps              | 290      |
|    time_elapsed     | 334      |
|    total_timesteps  | 132954   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.06e-07 |
|    n_updates        | 131953   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.09     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 396      |
|    fps              | 290      |
|    time_elapsed     | 338      |
|    total_timesteps  | 134310   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.27e-06 |
|    n_updates        | 133309   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.09     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 400      |
|    fps              | 291      |
|    time_elapsed     | 342      |
|    total_timesteps  | 135666   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.2e-07  |
|    n_updates        | 134665   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.1      |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 404      |
|    fps              | 291      |
|    time_elapsed     | 346      |
|    total_timesteps  | 137022   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.17e-07 |
|    n_updates        | 136021   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.1      |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 408      |
|    fps              | 291      |
|    time_elapsed     | 351      |
|    total_timesteps  | 138378   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 9.35e-07 |
|    n_updates        | 137377   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.1      |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 412      |
|    fps              | 291      |
|    time_elapsed     | 356      |
|    total_timesteps  | 139734   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.86e-07 |
|    n_updates        | 138733   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.1      |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 416      |
|    fps              | 291      |
|    time_elapsed     | 360      |
|    total_timesteps  | 141090   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.47e-07 |
|    n_updates        | 140089   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.1      |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 420      |
|    fps              | 291      |
|    time_elapsed     | 365      |
|    total_timesteps  | 142446   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.63e-07 |
|    n_updates        | 141445   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 424      |
|    fps              | 291      |
|    time_elapsed     | 369      |
|    total_timesteps  | 143802   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.88e-07 |
|    n_updates        | 142801   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 428      |
|    fps              | 292      |
|    time_elapsed     | 373      |
|    total_timesteps  | 145158   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.27e-07 |
|    n_updates        | 144157   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 432      |
|    fps              | 292      |
|    time_elapsed     | 377      |
|    total_timesteps  | 146514   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.07e-06 |
|    n_updates        | 145513   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 436      |
|    fps              | 292      |
|    time_elapsed     | 382      |
|    total_timesteps  | 147870   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.58e-07 |
|    n_updates        | 146869   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.1      |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 440      |
|    fps              | 292      |
|    time_elapsed     | 387      |
|    total_timesteps  | 149226   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.03e-07 |
|    n_updates        | 148225   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.1      |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 444      |
|    fps              | 292      |
|    time_elapsed     | 391      |
|    total_timesteps  | 150582   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.97e-07 |
|    n_updates        | 149581   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.1      |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 448      |
|    fps              | 292      |
|    time_elapsed     | 396      |
|    total_timesteps  | 151938   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.57e-07 |
|    n_updates        | 150937   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.1      |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 452      |
|    fps              | 292      |
|    time_elapsed     | 400      |
|    total_timesteps  | 153294   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.81e-07 |
|    n_updates        | 152293   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 456      |
|    fps              | 293      |
|    time_elapsed     | 404      |
|    total_timesteps  | 154650   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.02e-07 |
|    n_updates        | 153649   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 460      |
|    fps              | 293      |
|    time_elapsed     | 408      |
|    total_timesteps  | 156006   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 0.000275 |
|    n_updates        | 155005   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 464      |
|    fps              | 293      |
|    time_elapsed     | 413      |
|    total_timesteps  | 157362   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.49e-07 |
|    n_updates        | 156361   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 468      |
|    fps              | 293      |
|    time_elapsed     | 417      |
|    total_timesteps  | 158718   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.92e-07 |
|    n_updates        | 157717   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 472      |
|    fps              | 294      |
|    time_elapsed     | 421      |
|    total_timesteps  | 160074   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.44e-06 |
|    n_updates        | 159073   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 476      |
|    fps              | 294      |
|    time_elapsed     | 426      |
|    total_timesteps  | 161430   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.97e-07 |
|    n_updates        | 160429   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 480      |
|    fps              | 294      |
|    time_elapsed     | 430      |
|    total_timesteps  | 162786   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.72e-07 |
|    n_updates        | 161785   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 484      |
|    fps              | 294      |
|    time_elapsed     | 435      |
|    total_timesteps  | 164142   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.71e-06 |
|    n_updates        | 163141   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 488      |
|    fps              | 294      |
|    time_elapsed     | 439      |
|    total_timesteps  | 165498   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.38e-07 |
|    n_updates        | 164497   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 492      |
|    fps              | 294      |
|    time_elapsed     | 444      |
|    total_timesteps  | 166854   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.53e-07 |
|    n_updates        | 165853   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 496      |
|    fps              | 294      |
|    time_elapsed     | 448      |
|    total_timesteps  | 168210   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.69e-06 |
|    n_updates        | 167209   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 500      |
|    fps              | 294      |
|    time_elapsed     | 453      |
|    total_timesteps  | 169566   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.14e-07 |
|    n_updates        | 168565   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 504      |
|    fps              | 294      |
|    time_elapsed     | 457      |
|    total_timesteps  | 170922   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.03e-07 |
|    n_updates        | 169921   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 508      |
|    fps              | 294      |
|    time_elapsed     | 462      |
|    total_timesteps  | 172278   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.2e-07  |
|    n_updates        | 171277   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 512      |
|    fps              | 294      |
|    time_elapsed     | 466      |
|    total_timesteps  | 173634   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 8.62e-07 |
|    n_updates        | 172633   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 516      |
|    fps              | 294      |
|    time_elapsed     | 471      |
|    total_timesteps  | 174990   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.89e-07 |
|    n_updates        | 173989   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 520      |
|    fps              | 294      |
|    time_elapsed     | 476      |
|    total_timesteps  | 176346   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.52e-06 |
|    n_updates        | 175345   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 524      |
|    fps              | 294      |
|    time_elapsed     | 481      |
|    total_timesteps  | 177702   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.51e-07 |
|    n_updates        | 176701   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 528      |
|    fps              | 294      |
|    time_elapsed     | 486      |
|    total_timesteps  | 179058   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.09e-07 |
|    n_updates        | 178057   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 532      |
|    fps              | 293      |
|    time_elapsed     | 491      |
|    total_timesteps  | 180414   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.43e-07 |
|    n_updates        | 179413   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 536      |
|    fps              | 293      |
|    time_elapsed     | 496      |
|    total_timesteps  | 181770   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.19e-07 |
|    n_updates        | 180769   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 540      |
|    fps              | 293      |
|    time_elapsed     | 501      |
|    total_timesteps  | 183126   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.28e-07 |
|    n_updates        | 182125   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 544      |
|    fps              | 292      |
|    time_elapsed     | 507      |
|    total_timesteps  | 184482   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.67e-07 |
|    n_updates        | 183481   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 548      |
|    fps              | 292      |
|    time_elapsed     | 511      |
|    total_timesteps  | 185838   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.19e-07 |
|    n_updates        | 184837   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 552      |
|    fps              | 292      |
|    time_elapsed     | 516      |
|    total_timesteps  | 187194   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.89e-07 |
|    n_updates        | 186193   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 556      |
|    fps              | 292      |
|    time_elapsed     | 521      |
|    total_timesteps  | 188550   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.23e-07 |
|    n_updates        | 187549   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 560      |
|    fps              | 292      |
|    time_elapsed     | 526      |
|    total_timesteps  | 189906   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.54e-07 |
|    n_updates        | 188905   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 564      |
|    fps              | 291      |
|    time_elapsed     | 532      |
|    total_timesteps  | 191262   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.37e-07 |
|    n_updates        | 190261   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 568      |
|    fps              | 291      |
|    time_elapsed     | 537      |
|    total_timesteps  | 192618   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.88e-07 |
|    n_updates        | 191617   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 572      |
|    fps              | 291      |
|    time_elapsed     | 542      |
|    total_timesteps  | 193974   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.8e-07  |
|    n_updates        | 192973   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 576      |
|    fps              | 290      |
|    time_elapsed     | 547      |
|    total_timesteps  | 195330   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.85e-07 |
|    n_updates        | 194329   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 580      |
|    fps              | 290      |
|    time_elapsed     | 552      |
|    total_timesteps  | 196686   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.41e-07 |
|    n_updates        | 195685   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 584      |
|    fps              | 290      |
|    time_elapsed     | 557      |
|    total_timesteps  | 198042   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.44e-05 |
|    n_updates        | 197041   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 588      |
|    fps              | 290      |
|    time_elapsed     | 563      |
|    total_timesteps  | 199398   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.16e-07 |
|    n_updates        | 198397   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 592      |
|    fps              | 290      |
|    time_elapsed     | 567      |
|    total_timesteps  | 200754   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.6e-07  |
|    n_updates        | 199753   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 596      |
|    fps              | 290      |
|    time_elapsed     | 572      |
|    total_timesteps  | 202110   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.08e-06 |
|    n_updates        | 201109   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 600      |
|    fps              | 289      |
|    time_elapsed     | 577      |
|    total_timesteps  | 203466   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.07e-07 |
|    n_updates        | 202465   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 604      |
|    fps              | 289      |
|    time_elapsed     | 582      |
|    total_timesteps  | 204822   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.32e-07 |
|    n_updates        | 203821   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 608      |
|    fps              | 289      |
|    time_elapsed     | 587      |
|    total_timesteps  | 206178   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.19e-06 |
|    n_updates        | 205177   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 612      |
|    fps              | 289      |
|    time_elapsed     | 592      |
|    total_timesteps  | 207534   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.82e-07 |
|    n_updates        | 206533   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 616      |
|    fps              | 289      |
|    time_elapsed     | 597      |
|    total_timesteps  | 208890   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.17e-07 |
|    n_updates        | 207889   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 620      |
|    fps              | 288      |
|    time_elapsed     | 603      |
|    total_timesteps  | 210246   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.09e-06 |
|    n_updates        | 209245   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 624      |
|    fps              | 288      |
|    time_elapsed     | 608      |
|    total_timesteps  | 211602   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.51e-07 |
|    n_updates        | 210601   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 628      |
|    fps              | 288      |
|    time_elapsed     | 613      |
|    total_timesteps  | 212958   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.35e-07 |
|    n_updates        | 211957   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 632      |
|    fps              | 288      |
|    time_elapsed     | 618      |
|    total_timesteps  | 214314   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.44e-07 |
|    n_updates        | 213313   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 636      |
|    fps              | 288      |
|    time_elapsed     | 623      |
|    total_timesteps  | 215670   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.04e-07 |
|    n_updates        | 214669   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 640      |
|    fps              | 287      |
|    time_elapsed     | 628      |
|    total_timesteps  | 217026   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.65e-07 |
|    n_updates        | 216025   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 644      |
|    fps              | 287      |
|    time_elapsed     | 633      |
|    total_timesteps  | 218382   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.42e-07 |
|    n_updates        | 217381   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 648      |
|    fps              | 287      |
|    time_elapsed     | 639      |
|    total_timesteps  | 219738   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.23e-07 |
|    n_updates        | 218737   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 652      |
|    fps              | 287      |
|    time_elapsed     | 644      |
|    total_timesteps  | 221094   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.17e-07 |
|    n_updates        | 220093   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 656      |
|    fps              | 286      |
|    time_elapsed     | 649      |
|    total_timesteps  | 222450   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.58e-07 |
|    n_updates        | 221449   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 660      |
|    fps              | 286      |
|    time_elapsed     | 655      |
|    total_timesteps  | 223806   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.11e-07 |
|    n_updates        | 222805   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 664      |
|    fps              | 286      |
|    time_elapsed     | 660      |
|    total_timesteps  | 225162   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.91e-07 |
|    n_updates        | 224161   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 668      |
|    fps              | 285      |
|    time_elapsed     | 666      |
|    total_timesteps  | 226518   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.71e-07 |
|    n_updates        | 225517   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 672      |
|    fps              | 285      |
|    time_elapsed     | 671      |
|    total_timesteps  | 227874   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.68e-07 |
|    n_updates        | 226873   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 676      |
|    fps              | 285      |
|    time_elapsed     | 676      |
|    total_timesteps  | 229230   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.38e-07 |
|    n_updates        | 228229   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 680      |
|    fps              | 285      |
|    time_elapsed     | 681      |
|    total_timesteps  | 230586   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.13e-07 |
|    n_updates        | 229585   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 684      |
|    fps              | 285      |
|    time_elapsed     | 686      |
|    total_timesteps  | 231942   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.44e-07 |
|    n_updates        | 230941   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 688      |
|    fps              | 285      |
|    time_elapsed     | 691      |
|    total_timesteps  | 233298   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.96e-07 |
|    n_updates        | 232297   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 692      |
|    fps              | 285      |
|    time_elapsed     | 696      |
|    total_timesteps  | 234654   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.63e-07 |
|    n_updates        | 233653   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 696      |
|    fps              | 285      |
|    time_elapsed     | 701      |
|    total_timesteps  | 236010   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.49e-05 |
|    n_updates        | 235009   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 700      |
|    fps              | 284      |
|    time_elapsed     | 706      |
|    total_timesteps  | 237366   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.3e-07  |
|    n_updates        | 236365   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 704      |
|    fps              | 284      |
|    time_elapsed     | 712      |
|    total_timesteps  | 238722   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.47e-07 |
|    n_updates        | 237721   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 708      |
|    fps              | 284      |
|    time_elapsed     | 717      |
|    total_timesteps  | 240078   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.49e-06 |
|    n_updates        | 239077   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 712      |
|    fps              | 284      |
|    time_elapsed     | 722      |
|    total_timesteps  | 241434   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.53e-07 |
|    n_updates        | 240433   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 716      |
|    fps              | 284      |
|    time_elapsed     | 727      |
|    total_timesteps  | 242790   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.85e-07 |
|    n_updates        | 241789   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 720      |
|    fps              | 284      |
|    time_elapsed     | 732      |
|    total_timesteps  | 244146   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.4e-06  |
|    n_updates        | 243145   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 724      |
|    fps              | 284      |
|    time_elapsed     | 737      |
|    total_timesteps  | 245502   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.68e-07 |
|    n_updates        | 244501   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 728      |
|    fps              | 283      |
|    time_elapsed     | 742      |
|    total_timesteps  | 246858   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.02e-07 |
|    n_updates        | 245857   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 732      |
|    fps              | 283      |
|    time_elapsed     | 747      |
|    total_timesteps  | 248214   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.28e-07 |
|    n_updates        | 247213   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 736      |
|    fps              | 283      |
|    time_elapsed     | 752      |
|    total_timesteps  | 249570   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.46e-07 |
|    n_updates        | 248569   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 740      |
|    fps              | 283      |
|    time_elapsed     | 757      |
|    total_timesteps  | 250926   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.08e-07 |
|    n_updates        | 249925   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 744      |
|    fps              | 283      |
|    time_elapsed     | 761      |
|    total_timesteps  | 252282   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.34e-07 |
|    n_updates        | 251281   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 748      |
|    fps              | 283      |
|    time_elapsed     | 766      |
|    total_timesteps  | 253638   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.57e-07 |
|    n_updates        | 252637   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 752      |
|    fps              | 283      |
|    time_elapsed     | 771      |
|    total_timesteps  | 254994   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.47e-07 |
|    n_updates        | 253993   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 756      |
|    fps              | 283      |
|    time_elapsed     | 776      |
|    total_timesteps  | 256350   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.12e-07 |
|    n_updates        | 255349   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 760      |
|    fps              | 283      |
|    time_elapsed     | 781      |
|    total_timesteps  | 257706   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.37e-07 |
|    n_updates        | 256705   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 764      |
|    fps              | 283      |
|    time_elapsed     | 786      |
|    total_timesteps  | 259062   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.4e-07  |
|    n_updates        | 258061   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.14     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 768      |
|    fps              | 283      |
|    time_elapsed     | 790      |
|    total_timesteps  | 260418   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.34e-07 |
|    n_updates        | 259417   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 772      |
|    fps              | 283      |
|    time_elapsed     | 795      |
|    total_timesteps  | 261774   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.35e-07 |
|    n_updates        | 260773   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 776      |
|    fps              | 283      |
|    time_elapsed     | 800      |
|    total_timesteps  | 263130   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.47e-07 |
|    n_updates        | 262129   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 780      |
|    fps              | 283      |
|    time_elapsed     | 805      |
|    total_timesteps  | 264486   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.53e-07 |
|    n_updates        | 263485   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 784      |
|    fps              | 283      |
|    time_elapsed     | 810      |
|    total_timesteps  | 265842   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.67e-07 |
|    n_updates        | 264841   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 788      |
|    fps              | 283      |
|    time_elapsed     | 815      |
|    total_timesteps  | 267198   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.76e-07 |
|    n_updates        | 266197   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 792      |
|    fps              | 283      |
|    time_elapsed     | 820      |
|    total_timesteps  | 268554   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.13e-07 |
|    n_updates        | 267553   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 796      |
|    fps              | 283      |
|    time_elapsed     | 825      |
|    total_timesteps  | 269910   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.18e-07 |
|    n_updates        | 268909   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 800      |
|    fps              | 283      |
|    time_elapsed     | 830      |
|    total_timesteps  | 271266   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.9e-07  |
|    n_updates        | 270265   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 804      |
|    fps              | 283      |
|    time_elapsed     | 835      |
|    total_timesteps  | 272622   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.92e-07 |
|    n_updates        | 271621   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 808      |
|    fps              | 282      |
|    time_elapsed     | 840      |
|    total_timesteps  | 273978   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.11e-06 |
|    n_updates        | 272977   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 812      |
|    fps              | 282      |
|    time_elapsed     | 845      |
|    total_timesteps  | 275334   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.35e-07 |
|    n_updates        | 274333   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 816      |
|    fps              | 282      |
|    time_elapsed     | 851      |
|    total_timesteps  | 276690   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.09e-07 |
|    n_updates        | 275689   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 820      |
|    fps              | 282      |
|    time_elapsed     | 856      |
|    total_timesteps  | 278046   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.28e-05 |
|    n_updates        | 277045   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 824      |
|    fps              | 282      |
|    time_elapsed     | 862      |
|    total_timesteps  | 279402   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.03e-07 |
|    n_updates        | 278401   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 828      |
|    fps              | 282      |
|    time_elapsed     | 867      |
|    total_timesteps  | 280758   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.02e-07 |
|    n_updates        | 279757   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 832      |
|    fps              | 282      |
|    time_elapsed     | 872      |
|    total_timesteps  | 282114   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.34e-06 |
|    n_updates        | 281113   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.11     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 836      |
|    fps              | 281      |
|    time_elapsed     | 878      |
|    total_timesteps  | 283470   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.47e-07 |
|    n_updates        | 282469   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 840      |
|    fps              | 281      |
|    time_elapsed     | 883      |
|    total_timesteps  | 284826   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.2e-07  |
|    n_updates        | 283825   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 844      |
|    fps              | 281      |
|    time_elapsed     | 888      |
|    total_timesteps  | 286182   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 7.85e-07 |
|    n_updates        | 285181   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 848      |
|    fps              | 281      |
|    time_elapsed     | 894      |
|    total_timesteps  | 287538   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.33e-07 |
|    n_updates        | 286537   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 852      |
|    fps              | 280      |
|    time_elapsed     | 900      |
|    total_timesteps  | 288894   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.61e-07 |
|    n_updates        | 287893   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 856      |
|    fps              | 280      |
|    time_elapsed     | 906      |
|    total_timesteps  | 290250   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.18e-06 |
|    n_updates        | 289249   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 860      |
|    fps              | 280      |
|    time_elapsed     | 912      |
|    total_timesteps  | 291606   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4e-07    |
|    n_updates        | 290605   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 864      |
|    fps              | 280      |
|    time_elapsed     | 916      |
|    total_timesteps  | 292962   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.06e-07 |
|    n_updates        | 291961   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.12     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 868      |
|    fps              | 280      |
|    time_elapsed     | 921      |
|    total_timesteps  | 294318   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 8.57e-07 |
|    n_updates        | 293317   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 872      |
|    fps              | 280      |
|    time_elapsed     | 925      |
|    total_timesteps  | 295674   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 5.17e-07 |
|    n_updates        | 294673   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 876      |
|    fps              | 280      |
|    time_elapsed     | 931      |
|    total_timesteps  | 297030   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 9.26e-07 |
|    n_updates        | 296029   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.14     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 880      |
|    fps              | 280      |
|    time_elapsed     | 936      |
|    total_timesteps  | 298386   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.79e-07 |
|    n_updates        | 297385   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 884      |
|    fps              | 280      |
|    time_elapsed     | 940      |
|    total_timesteps  | 299742   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 6.39e-07 |
|    n_updates        | 298741   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.14     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 888      |
|    fps              | 280      |
|    time_elapsed     | 945      |
|    total_timesteps  | 301098   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.21e-07 |
|    n_updates        | 300097   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 892      |
|    fps              | 280      |
|    time_elapsed     | 950      |
|    total_timesteps  | 302454   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.34e-07 |
|    n_updates        | 301453   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 896      |
|    fps              | 280      |
|    time_elapsed     | 955      |
|    total_timesteps  | 303810   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.48e-07 |
|    n_updates        | 302809   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.14     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 900      |
|    fps              | 280      |
|    time_elapsed     | 959      |
|    total_timesteps  | 305166   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.69e-07 |
|    n_updates        | 304165   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.14     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 904      |
|    fps              | 280      |
|    time_elapsed     | 963      |
|    total_timesteps  | 306522   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.79e-07 |
|    n_updates        | 305521   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.14     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 908      |
|    fps              | 280      |
|    time_elapsed     | 968      |
|    total_timesteps  | 307878   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.24e-07 |
|    n_updates        | 306877   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.13     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 912      |
|    fps              | 280      |
|    time_elapsed     | 972      |
|    total_timesteps  | 309234   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.4e-07  |
|    n_updates        | 308233   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.14     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 916      |
|    fps              | 280      |
|    time_elapsed     | 977      |
|    total_timesteps  | 310590   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.58e-07 |
|    n_updates        | 309589   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.14     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 920      |
|    fps              | 281      |
|    time_elapsed     | 981      |
|    total_timesteps  | 311946   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.71e-07 |
|    n_updates        | 310945   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.14     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 924      |
|    fps              | 281      |
|    time_elapsed     | 986      |
|    total_timesteps  | 313302   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.11e-07 |
|    n_updates        | 312301   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.14     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 928      |
|    fps              | 281      |
|    time_elapsed     | 990      |
|    total_timesteps  | 314658   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.23e-07 |
|    n_updates        | 313657   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.15     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 932      |
|    fps              | 281      |
|    time_elapsed     | 994      |
|    total_timesteps  | 316014   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.71e-05 |
|    n_updates        | 315013   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.15     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 936      |
|    fps              | 281      |
|    time_elapsed     | 999      |
|    total_timesteps  | 317370   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.37e-07 |
|    n_updates        | 316369   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.15     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 940      |
|    fps              | 281      |
|    time_elapsed     | 1004     |
|    total_timesteps  | 318726   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.54e-07 |
|    n_updates        | 317725   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.15     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 944      |
|    fps              | 281      |
|    time_elapsed     | 1008     |
|    total_timesteps  | 320082   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.8e-06  |
|    n_updates        | 319081   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.15     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 948      |
|    fps              | 281      |
|    time_elapsed     | 1013     |
|    total_timesteps  | 321438   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.46e-07 |
|    n_updates        | 320437   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.15     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 952      |
|    fps              | 281      |
|    time_elapsed     | 1017     |
|    total_timesteps  | 322794   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.36e-07 |
|    n_updates        | 321793   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.15     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 956      |
|    fps              | 281      |
|    time_elapsed     | 1021     |
|    total_timesteps  | 324150   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.48e-06 |
|    n_updates        | 323149   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.15     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 960      |
|    fps              | 282      |
|    time_elapsed     | 1026     |
|    total_timesteps  | 325506   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.45e-07 |
|    n_updates        | 324505   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.15     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 964      |
|    fps              | 282      |
|    time_elapsed     | 1031     |
|    total_timesteps  | 326862   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.23e-07 |
|    n_updates        | 325861   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.15     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 968      |
|    fps              | 282      |
|    time_elapsed     | 1035     |
|    total_timesteps  | 328218   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 4.15e-07 |
|    n_updates        | 327217   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.14     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 972      |
|    fps              | 282      |
|    time_elapsed     | 1040     |
|    total_timesteps  | 329574   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 3.12e-07 |
|    n_updates        | 328573   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.14     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 976      |
|    fps              | 282      |
|    time_elapsed     | 1045     |
|    total_timesteps  | 330930   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.42e-07 |
|    n_updates        | 329929   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.15     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 980      |
|    fps              | 282      |
|    time_elapsed     | 1050     |
|    total_timesteps  | 332286   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 2.22e-07 |
|    n_updates        | 331285   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.15     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 984      |
|    fps              | 282      |
|    time_elapsed     | 1054     |
|    total_timesteps  | 333642   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.68e-07 |
|    n_updates        | 332641   |
----------------------------------

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 339      |
|    ep_rew_mean      | 5.15     |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 988      |
|    fps              | 282      |
|    time_elapsed     | 1059     |
|    total_timesteps  | 334998   |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 1.17e-07 |
|    n_updates        | 333997   |
----------------------------------

Output()

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 339      |
|    ep_rew_mean        | 0.182    |
| time/                 |          |
|    fps                | 710      |
|    iterations         | 100      |
|    time_elapsed       | 36       |
|    total_timesteps    | 40704    |
| train/                |          |
|    entropy_loss       | -1.94    |
|    explained_variance | 0.769    |
|    learning_rate      | 0.0005   |
|    n_updates          | 158      |
|    policy_loss        | 0.081    |
|    value_loss         | 0.00455  |
------------------------------------

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 339      |
|    ep_rew_mean        | 0.214    |
| time/                 |          |
|    fps                | 711      |
|    iterations         | 200      |
|    time_elapsed       | 71       |
|    total_timesteps    | 66304    |
| train/                |          |
|    entropy_loss       | -1.94    |
|    explained_variance | 0.594    |
|    learning_rate      | 0.0005   |
|    n_updates          | 258      |
|    policy_loss        | -0.0477  |
|    value_loss         | 0.00687  |
------------------------------------

Output()

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 339      |
|    ep_rew_mean     | 0.514    |
| time/              |          |
|    fps             | 721      |
|    iterations      | 1        |
|    time_elapsed    | 2        |
|    total_timesteps | 26624    |
---------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 0.568       |
| time/                   |             |
|    fps                  | 689         |
|    iterations           | 2           |
|    time_elapsed         | 5           |
|    total_timesteps      | 28672       |
| train/                  |             |
|    approx_kl            | 0.013309254 |
|    clip_fraction        | 0.102       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.64       |
|    explained_variance   | 0.853       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0648     |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.0299     |
|    value_loss           | 0.00153     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 0.634       |
| time/                   |             |
|    fps                  | 681         |
|    iterations           | 3           |
|    time_elapsed         | 9           |
|    total_timesteps      | 30720       |
| train/                  |             |
|    approx_kl            | 0.011553093 |
|    clip_fraction        | 0.0737      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.59       |
|    explained_variance   | 0.918       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0588     |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.0287     |
|    value_loss           | 0.0015      |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 0.693       |
| time/                   |             |
|    fps                  | 673         |
|    iterations           | 4           |
|    time_elapsed         | 12          |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.010442312 |
|    clip_fraction        | 0.0852      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.53       |
|    explained_variance   | 0.944       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0544     |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.0273     |
|    value_loss           | 0.00123     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 0.769       |
| time/                   |             |
|    fps                  | 676         |
|    iterations           | 5           |
|    time_elapsed         | 15          |
|    total_timesteps      | 34816       |
| train/                  |             |
|    approx_kl            | 0.010505447 |
|    clip_fraction        | 0.0902      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.51       |
|    explained_variance   | 0.953       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0594     |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.0294     |
|    value_loss           | 0.00132     |
-----------------------------------------

------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 339          |
|    ep_rew_mean          | 0.873        |
| time/                   |              |
|    fps                  | 665          |
|    iterations           | 6            |
|    time_elapsed         | 18           |
|    total_timesteps      | 36864        |
| train/                  |              |
|    approx_kl            | 0.0129664615 |
|    clip_fraction        | 0.0998       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.48        |
|    explained_variance   | 0.971        |
|    learning_rate        | 0.0003       |
|    loss                 | -0.06        |
|    n_updates            | 170          |
|    policy_gradient_loss | -0.0303      |
|    value_loss           | 0.00113      |
------------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 0.967       |
| time/                   |             |
|    fps                  | 658         |
|    iterations           | 7           |
|    time_elapsed         | 21          |
|    total_timesteps      | 38912       |
| train/                  |             |
|    approx_kl            | 0.011436636 |
|    clip_fraction        | 0.0943      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.45       |
|    explained_variance   | 0.966       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0651     |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.029      |
|    value_loss           | 0.00146     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 1.06        |
| time/                   |             |
|    fps                  | 650         |
|    iterations           | 8           |
|    time_elapsed         | 25          |
|    total_timesteps      | 40960       |
| train/                  |             |
|    approx_kl            | 0.010259462 |
|    clip_fraction        | 0.0773      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.41       |
|    explained_variance   | 0.963       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0487     |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.0273     |
|    value_loss           | 0.00177     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 1.18        |
| time/                   |             |
|    fps                  | 644         |
|    iterations           | 9           |
|    time_elapsed         | 28          |
|    total_timesteps      | 43008       |
| train/                  |             |
|    approx_kl            | 0.011784676 |
|    clip_fraction        | 0.104       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.38       |
|    explained_variance   | 0.974       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0469     |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.0293     |
|    value_loss           | 0.00179     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 339        |
|    ep_rew_mean          | 1.3        |
| time/                   |            |
|    fps                  | 646        |
|    iterations           | 10         |
|    time_elapsed         | 31         |
|    total_timesteps      | 45056      |
| train/                  |            |
|    approx_kl            | 0.01240344 |
|    clip_fraction        | 0.0927     |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.34      |
|    explained_variance   | 0.979      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0465    |
|    n_updates            | 210        |
|    policy_gradient_loss | -0.0289    |
|    value_loss           | 0.00187    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 1.41        |
| time/                   |             |
|    fps                  | 641         |
|    iterations           | 11          |
|    time_elapsed         | 35          |
|    total_timesteps      | 47104       |
| train/                  |             |
|    approx_kl            | 0.009791106 |
|    clip_fraction        | 0.0831      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.31       |
|    explained_variance   | 0.985       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0512     |
|    n_updates            | 220         |
|    policy_gradient_loss | -0.0283     |
|    value_loss           | 0.0015      |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 1.52        |
| time/                   |             |
|    fps                  | 642         |
|    iterations           | 12          |
|    time_elapsed         | 38          |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.012166691 |
|    clip_fraction        | 0.101       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.27       |
|    explained_variance   | 0.99        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0573     |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.0292     |
|    value_loss           | 0.00139     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 1.62        |
| time/                   |             |
|    fps                  | 645         |
|    iterations           | 13          |
|    time_elapsed         | 41          |
|    total_timesteps      | 51200       |
| train/                  |             |
|    approx_kl            | 0.013563622 |
|    clip_fraction        | 0.105       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.24       |
|    explained_variance   | 0.99        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0575     |
|    n_updates            | 240         |
|    policy_gradient_loss | -0.0319     |
|    value_loss           | 0.00149     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 1.71        |
| time/                   |             |
|    fps                  | 648         |
|    iterations           | 14          |
|    time_elapsed         | 44          |
|    total_timesteps      | 53248       |
| train/                  |             |
|    approx_kl            | 0.011144719 |
|    clip_fraction        | 0.108       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.22       |
|    explained_variance   | 0.994       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0546     |
|    n_updates            | 250         |
|    policy_gradient_loss | -0.0297     |
|    value_loss           | 0.00146     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 1.8         |
| time/                   |             |
|    fps                  | 653         |
|    iterations           | 15          |
|    time_elapsed         | 47          |
|    total_timesteps      | 55296       |
| train/                  |             |
|    approx_kl            | 0.011442894 |
|    clip_fraction        | 0.0942      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.2        |
|    explained_variance   | 0.994       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0583     |
|    n_updates            | 260         |
|    policy_gradient_loss | -0.0305     |
|    value_loss           | 0.00123     |
-----------------------------------------

------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 339          |
|    ep_rew_mean          | 1.9          |
| time/                   |              |
|    fps                  | 659          |
|    iterations           | 16           |
|    time_elapsed         | 49           |
|    total_timesteps      | 57344        |
| train/                  |              |
|    approx_kl            | 0.0122513855 |
|    clip_fraction        | 0.119        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.16        |
|    explained_variance   | 0.997        |
|    learning_rate        | 0.0003       |
|    loss                 | -0.05        |
|    n_updates            | 270          |
|    policy_gradient_loss | -0.0303      |
|    value_loss           | 0.000795     |
------------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 1.99        |
| time/                   |             |
|    fps                  | 662         |
|    iterations           | 17          |
|    time_elapsed         | 52          |
|    total_timesteps      | 59392       |
| train/                  |             |
|    approx_kl            | 0.016385555 |
|    clip_fraction        | 0.14        |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.11       |
|    explained_variance   | 0.998       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0585     |
|    n_updates            | 280         |
|    policy_gradient_loss | -0.0338     |
|    value_loss           | 0.000805    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 2.09        |
| time/                   |             |
|    fps                  | 663         |
|    iterations           | 18          |
|    time_elapsed         | 55          |
|    total_timesteps      | 61440       |
| train/                  |             |
|    approx_kl            | 0.012976414 |
|    clip_fraction        | 0.116       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.08       |
|    explained_variance   | 0.997       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0529     |
|    n_updates            | 290         |
|    policy_gradient_loss | -0.0272     |
|    value_loss           | 0.00105     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 2.18        |
| time/                   |             |
|    fps                  | 664         |
|    iterations           | 19          |
|    time_elapsed         | 58          |
|    total_timesteps      | 63488       |
| train/                  |             |
|    approx_kl            | 0.014798129 |
|    clip_fraction        | 0.114       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.04       |
|    explained_variance   | 0.998       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0594     |
|    n_updates            | 300         |
|    policy_gradient_loss | -0.031      |
|    value_loss           | 0.000941    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 2.27        |
| time/                   |             |
|    fps                  | 663         |
|    iterations           | 20          |
|    time_elapsed         | 61          |
|    total_timesteps      | 65536       |
| train/                  |             |
|    approx_kl            | 0.012536347 |
|    clip_fraction        | 0.109       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.993      |
|    explained_variance   | 0.998       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.048      |
|    n_updates            | 310         |
|    policy_gradient_loss | -0.0307     |
|    value_loss           | 0.00063     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 2.35        |
| time/                   |             |
|    fps                  | 666         |
|    iterations           | 21          |
|    time_elapsed         | 64          |
|    total_timesteps      | 67584       |
| train/                  |             |
|    approx_kl            | 0.014566287 |
|    clip_fraction        | 0.116       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.963      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0583     |
|    n_updates            | 320         |
|    policy_gradient_loss | -0.0303     |
|    value_loss           | 0.000589    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 2.44        |
| time/                   |             |
|    fps                  | 668         |
|    iterations           | 22          |
|    time_elapsed         | 67          |
|    total_timesteps      | 69632       |
| train/                  |             |
|    approx_kl            | 0.012037568 |
|    clip_fraction        | 0.104       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.929      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0553     |
|    n_updates            | 330         |
|    policy_gradient_loss | -0.028      |
|    value_loss           | 0.000733    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 2.54        |
| time/                   |             |
|    fps                  | 670         |
|    iterations           | 23          |
|    time_elapsed         | 70          |
|    total_timesteps      | 71680       |
| train/                  |             |
|    approx_kl            | 0.015355796 |
|    clip_fraction        | 0.107       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.888      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0429     |
|    n_updates            | 340         |
|    policy_gradient_loss | -0.029      |
|    value_loss           | 0.000666    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 2.65        |
| time/                   |             |
|    fps                  | 671         |
|    iterations           | 24          |
|    time_elapsed         | 73          |
|    total_timesteps      | 73728       |
| train/                  |             |
|    approx_kl            | 0.016019214 |
|    clip_fraction        | 0.117       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.848      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.053      |
|    n_updates            | 350         |
|    policy_gradient_loss | -0.0312     |
|    value_loss           | 0.000396    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 2.75        |
| time/                   |             |
|    fps                  | 671         |
|    iterations           | 25          |
|    time_elapsed         | 76          |
|    total_timesteps      | 75776       |
| train/                  |             |
|    approx_kl            | 0.015700651 |
|    clip_fraction        | 0.127       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.82       |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0484     |
|    n_updates            | 360         |
|    policy_gradient_loss | -0.0293     |
|    value_loss           | 0.000389    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 339        |
|    ep_rew_mean          | 2.85       |
| time/                   |            |
|    fps                  | 672        |
|    iterations           | 26         |
|    time_elapsed         | 79         |
|    total_timesteps      | 77824      |
| train/                  |            |
|    approx_kl            | 0.01602672 |
|    clip_fraction        | 0.122      |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.787     |
|    explained_variance   | 0.999      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0493    |
|    n_updates            | 370        |
|    policy_gradient_loss | -0.0279    |
|    value_loss           | 0.00042    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 2.95        |
| time/                   |             |
|    fps                  | 671         |
|    iterations           | 27          |
|    time_elapsed         | 82          |
|    total_timesteps      | 79872       |
| train/                  |             |
|    approx_kl            | 0.013059264 |
|    clip_fraction        | 0.113       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.748      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0366     |
|    n_updates            | 380         |
|    policy_gradient_loss | -0.0262     |
|    value_loss           | 0.000387    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 3.05        |
| time/                   |             |
|    fps                  | 672         |
|    iterations           | 28          |
|    time_elapsed         | 85          |
|    total_timesteps      | 81920       |
| train/                  |             |
|    approx_kl            | 0.013056289 |
|    clip_fraction        | 0.104       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.719      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0426     |
|    n_updates            | 390         |
|    policy_gradient_loss | -0.0255     |
|    value_loss           | 0.000421    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 3.14        |
| time/                   |             |
|    fps                  | 668         |
|    iterations           | 29          |
|    time_elapsed         | 88          |
|    total_timesteps      | 83968       |
| train/                  |             |
|    approx_kl            | 0.017051253 |
|    clip_fraction        | 0.117       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.689      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0483     |
|    n_updates            | 400         |
|    policy_gradient_loss | -0.028      |
|    value_loss           | 0.000388    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 3.25        |
| time/                   |             |
|    fps                  | 669         |
|    iterations           | 30          |
|    time_elapsed         | 91          |
|    total_timesteps      | 86016       |
| train/                  |             |
|    approx_kl            | 0.016545326 |
|    clip_fraction        | 0.113       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.666      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0387     |
|    n_updates            | 410         |
|    policy_gradient_loss | -0.0252     |
|    value_loss           | 0.000412    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 3.35        |
| time/                   |             |
|    fps                  | 670         |
|    iterations           | 31          |
|    time_elapsed         | 94          |
|    total_timesteps      | 88064       |
| train/                  |             |
|    approx_kl            | 0.013422107 |
|    clip_fraction        | 0.109       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.64       |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0466     |
|    n_updates            | 420         |
|    policy_gradient_loss | -0.0256     |
|    value_loss           | 0.000342    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 3.45        |
| time/                   |             |
|    fps                  | 670         |
|    iterations           | 32          |
|    time_elapsed         | 97          |
|    total_timesteps      | 90112       |
| train/                  |             |
|    approx_kl            | 0.015714442 |
|    clip_fraction        | 0.113       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.614      |
|    explained_variance   | 1           |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0399     |
|    n_updates            | 430         |
|    policy_gradient_loss | -0.0262     |
|    value_loss           | 0.000347    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 3.54        |
| time/                   |             |
|    fps                  | 668         |
|    iterations           | 33          |
|    time_elapsed         | 101         |
|    total_timesteps      | 92160       |
| train/                  |             |
|    approx_kl            | 0.013076761 |
|    clip_fraction        | 0.0996      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.592      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0299     |
|    n_updates            | 440         |
|    policy_gradient_loss | -0.0238     |
|    value_loss           | 0.000305    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 3.64        |
| time/                   |             |
|    fps                  | 668         |
|    iterations           | 34          |
|    time_elapsed         | 104         |
|    total_timesteps      | 94208       |
| train/                  |             |
|    approx_kl            | 0.014967238 |
|    clip_fraction        | 0.108       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.562      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0404     |
|    n_updates            | 450         |
|    policy_gradient_loss | -0.0244     |
|    value_loss           | 0.000316    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 339         |
|    ep_rew_mean          | 3.72        |
| time/                   |             |
|    fps                  | 670         |
|    iterations           | 35          |
|    time_elapsed         | 106         |
|    total_timesteps      | 96256       |
| train/                  |             |
|    approx_kl            | 0.018089993 |
|    clip_fraction        | 0.112       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.541      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0383     |
|    n_updates            | 460         |
|    policy_gradient_loss | -0.0243     |
|    value_loss           | 0.000325    |
-----------------------------------------

In [ ]:
validation_export_env = make_rl_env(prepared, split="validation", seq_len=SEQ_LEN, config=EVAL_CONFIG)
locked_test_export_env = make_rl_env(prepared, split="locked_test", seq_len=SEQ_LEN, config=EVAL_CONFIG)

export_rows = []
action_mix_tables = []

for policy_name, model in models.items():
    policy_agent = AttentionAgentAdapter(model) if policy_name == "ATTENTION_DQN" else model
    policy_key = policy_name.lower()

    val_actions = rollout_agent_on_split(policy_agent, validation_export_env, frame, "validation")
    test_actions = rollout_agent_on_split(policy_agent, locked_test_export_env, frame, "locked_test")

    val_path = save_action_frame(
        val_actions,
        OUTPUT_DIR / f"{policy_key}_validation_actions_finetuned.csv",
    )
    test_path = save_action_frame(
        test_actions,
        OUTPUT_DIR / f"{policy_key}_locked_test_actions_finetuned.csv",
    )

    export_rows.append(
        {
            "policy": policy_name,
            "validation_actions": str(val_path.relative_to(REPO_ROOT)),
            "locked_test_actions": str(test_path.relative_to(REPO_ROOT)),
        }
    )

    mix = pd.DataFrame(
        {
            "validation": val_actions["action_name"].value_counts(),
            "locked_test": test_actions["action_name"].value_counts(),
        }
    ).fillna(0).astype(int)
    mix["policy"] = policy_name
    action_mix_tables.append(mix.reset_index().rename(columns={"index": "action_name"}))

exports_df = pd.DataFrame(export_rows)
display(exports_df)

action_mix = pd.concat(action_mix_tables, ignore_index=True)
display(action_mix.sort_values(["policy", "action_name"]).reset_index(drop=True))

# Publish canonical aliases using the best validation policy from the comparison cell.
if "best_policy_validation" in globals():
    best_policy = best_policy_validation
else:
    fallback_rank = finetuned_table.loc[finetuned_table["split"] == "validation", ["policy", "sharpe_ratio"]].copy()
    fallback_rank = fallback_rank.sort_values("sharpe_ratio", ascending=False, na_position="last")
    best_policy = str(fallback_rank.iloc[0]["policy"])

best_key = best_policy.lower()
best_val_src = OUTPUT_DIR / f"{best_key}_validation_actions_finetuned.csv"
best_test_src = OUTPUT_DIR / f"{best_key}_locked_test_actions_finetuned.csv"
best_val_dst = OUTPUT_DIR / "rl_validation_actions_finetuned.csv"
best_test_dst = OUTPUT_DIR / "rl_locked_test_actions_finetuned.csv"
best_val_dst.write_text(best_val_src.read_text(encoding="utf-8"), encoding="utf-8")
best_test_dst.write_text(best_test_src.read_text(encoding="utf-8"), encoding="utf-8")

print(f"Best validation policy (for canonical exports): {best_policy}")
print("Canonical exports:")
print(" ", best_val_dst.relative_to(REPO_ROOT))
print(" ", best_test_dst.relative_to(REPO_ROOT))